namespace BaseHmiTypes.Screens.Controls;

public enum HmiAlarmColumnType
{
    Unknown,
    AcknowledgedSymbol,
    ActiveSymbol,
    AlarmTime,
    AcknowledgmentTime,
    Message,
    TriggerLabel,
    TriggerValue,
    AlarmQuantity,
    AccumulatedTime,
    AlarmState,
    AlarmClass,
    AlarmName,
    AlarmShortName,
    Area,
    ConditionName,
    CurrentValue,
    EventCategory,
    EventSource,
    EventTime,
    Group,
    InAlarmTime,
    LimitValue,
    LiveDataValue,
    OutOfAlarmTime,
    Priority,
    ServerName,
    Severity,
    Tag1Value,
    Tag2Value,
    Tag3Value,
    Tag4Value
}
