import { HmiColor, HmiFont, HmiLineStyle, HmiProperty } from "../base.js";
import { HmiMultilingualText } from "../../common/HmiMultilingualText.js";
import { HmiControlWindowBase } from "../base/HmiControlWindowBase.js";
import { HmiObjectType } from "../base/HmiObjectType.js";
import { HmiAlarmColumn } from "./HmiAlarmColumn.js";
import { HmiAlarmConditionPresentation } from "./HmiAlarmConditionPresentation.js";
import { HmiAlarmSelectedIndicator } from "./HmiAlarmSelectedIndicator.js";
import { HmiAlarmListMode } from "./HmiAlarmListMode.js";
import { HmiBorderStyle } from "./HmiBorderStyle.js";
import { HmiAlarmViewKind } from "./HmiAlarmViewKind.js";
import { HmiAlarmTimePrecision } from "./HmiAlarmTimePrecision.js";
import { HmiAlarmRowDoubleClickAction } from "./HmiAlarmRowDoubleClickAction.js";
import { HmiAlarmToolbarButton } from "./HmiAlarmToolbarButton.js";
import { HmiAlarmStatusBarPanel } from "./HmiAlarmStatusBarPanel.js";
import { HmiAlarmEventSubscription } from "./HmiAlarmEventSubscription.js";
import { HmiAlarmBlinkRate } from "./HmiAlarmBlinkRate.js";
import { HmiAlarmStateAppearance } from "./HmiAlarmStateAppearance.js";
import { HmiAlarmSortCriterion } from "./HmiAlarmSortCriterion.js";
import { HmiAlarmFilterExpression } from "./HmiAlarmFilterExpression.js";

export class HmiAlarmControl extends HmiControlWindowBase {
  constructor() {
    super();
    this.hmiObjectType = HmiObjectType.HmiAlarmControl;
  }

  suppressFlashing?: HmiProperty<boolean>;
  viewKind = HmiAlarmViewKind.Unknown;
  acknowledgmentFlashingRate?: HmiProperty<number>;
  resetFlashingRate?: HmiProperty<number>;
  numberOfRows?: HmiProperty<number>;
  wrapAround?: HmiProperty<boolean>;
  linesPerAlarm?: HmiProperty<number>;
  selectedAlarmIndicator?: HmiProperty<HmiAlarmSelectedIndicator>;
  wordWrap?: HmiProperty<boolean>;
  readonly filteredTriggers: string[] = [];
  useAlarmIdentifier?: HmiProperty<boolean>;
  alarmIdentifier?: HmiProperty<number>;
  readonly conditions: HmiAlarmConditionPresentation[] = [];
  readonly columnDefinitions: HmiAlarmColumn[] = [];
  readonly toolbarButtons: HmiAlarmToolbarButton[] = [];
  showHeader?: HmiProperty<boolean>;
  showTitle?: HmiProperty<boolean>;
  listMode?: HmiProperty<HmiAlarmListMode>;
  title?: HmiMultilingualText;
  allAlarmsTitle?: HmiMultilingualText;
  activeAlarmsTitle?: HmiMultilingualText;
  pastAlarmsTitle?: HmiMultilingualText;
  showAlarmTime?: HmiProperty<boolean>;
  showAcknowledgmentTime?: HmiProperty<boolean>;
  showAcknowledgeButton?: HmiProperty<boolean>;
  showHelpButton?: HmiProperty<boolean>;
  showToolbar?: HmiProperty<boolean>;
  showDetailsButton?: HmiProperty<boolean>;
  showEnableDisableButtons?: HmiProperty<boolean>;
  showSuppressUnsuppressButtons?: HmiProperty<boolean>;
  showShelveUnshelveButtons?: HmiProperty<boolean>;
  showAreaTree?: HmiProperty<boolean>;
  areaTreeWidth?: HmiProperty<number>;
  rootArea?: HmiProperty<string>;
  nameFilter?: HmiProperty<string>;
  statusFilter?: HmiProperty<string>;
  readOnlyMode?: HmiProperty<boolean>;
  displayErrorsInDialog?: HmiProperty<boolean>;
  displayMilliseconds?: HmiProperty<boolean>;
  timePrecision?: HmiProperty<HmiAlarmTimePrecision>;
  context?: HmiProperty<string>;
  listBackgroundColor?: HmiProperty<HmiColor>;
  disabledColumnWidth?: HmiProperty<number>;
  nameColumnWidth?: HmiProperty<number>;
  pathColumnWidth?: HmiProperty<number>;
  shelvedColumnWidth?: HmiProperty<number>;
  suppressedColumnWidth?: HmiProperty<number>;
  detailsPaneAllowResize?: HmiProperty<boolean>;
  detailsPaneBackgroundColor?: HmiProperty<HmiColor>;
  detailsPaneForegroundColor?: HmiProperty<HmiColor>;
  detailsPaneFont?: HmiFont;
  detailsPaneHeight?: HmiProperty<number>;
  detailsPaneVisible?: HmiProperty<boolean>;
  displayEventContextMenu?: HmiProperty<boolean>;
  allowColumnResize?: HmiProperty<boolean>;
  allowSortByColumn?: HmiProperty<boolean>;
  rowDoubleClickAction?: HmiProperty<HmiAlarmRowDoubleClickAction>;
  sendSelectedAlarmMessageIdToTag?: HmiProperty<boolean>;
  selectedAlarmMessageIdTag?: HmiProperty<string>;
  defaultFilter?: HmiProperty<string>;
  filterDefinition?: HmiProperty<string>;
  filterExpression?: HmiAlarmFilterExpression;
  filterName?: HmiProperty<string>;
  gridBackgroundColor?: HmiProperty<HmiColor>;
  showHorizontalGridLines?: HmiProperty<boolean>;
  showVerticalGridLines?: HmiProperty<boolean>;
  showHorizontalScrollbar?: HmiProperty<boolean>;
  showVerticalScrollbar?: HmiProperty<boolean>;
  showOutOfServiceAlarms?: HmiProperty<boolean>;
  sortOrder?: HmiProperty<string>;
  readonly sortCriteria: HmiAlarmSortCriterion[] = [];
  showStatusBar?: HmiProperty<boolean>;
  readonly statusBarPanels: HmiAlarmStatusBarPanel[] = [];
  statusBarFont?: HmiFont;
  statusBarIconSize?: HmiProperty<string>;
  readonly eventSubscriptions: HmiAlarmEventSubscription[] = [];
  readonly stateAppearances: HmiAlarmStateAppearance[] = [];
  alarmBlinkRate?: HmiProperty<HmiAlarmBlinkRate>;
  alarmBlinkRateSource?: string;
  alarmSoundRepeatIntervalSeconds?: HmiProperty<number>;
  recordLimit?: HmiProperty<number>;
  whereClause?: HmiProperty<string>;
  historyDatabase?: HmiProperty<string>;
  displayReportOnStartup?: HmiProperty<boolean>;
  showTooltips?: HmiProperty<boolean>;
  showQualityMessages?: HmiProperty<boolean>;
  showBorder?: HmiProperty<boolean>;
  iconStyle?: HmiProperty<string>;
  toolbarForegroundColor?: HmiProperty<HmiColor>;
  toolbarBackgroundColor?: HmiProperty<HmiColor>;
  toolbarIconSize?: HmiProperty<string>;
  defaultPrintFont?: HmiFont;
  showPendingAlarms?: HmiProperty<boolean>;
  showAlarmsToAcknowledge?: HmiProperty<boolean>;
  sortByTimeEnabled?: HmiProperty<boolean>;
  messageAreaWidth?: HmiProperty<number>;
  messageAreaHeight?: HmiProperty<number>;
  alarmClasses?: HmiProperty<number[]>;
  columns?: HmiProperty<number[]>;
  columnOrder?: HmiProperty<number[]>;
  columnWidth?: HmiProperty<number[]>;
  minimumColumnWidth?: HmiProperty<number[]>;
  tableBackgroundColor?: HmiProperty<HmiColor>;
  tableForegroundColor?: HmiProperty<HmiColor>;
  selectionBackgroundColor?: HmiProperty<HmiColor>;
  selectionForegroundColor?: HmiProperty<HmiColor>;
  useAlarmColors?: HmiProperty<boolean>;
  tableHeaderBackgroundColor?: HmiProperty<HmiColor>;
  tableHeaderForegroundColor?: HmiProperty<HmiColor>;
  tableHeaderBorderBackgroundColor?: HmiProperty<HmiColor>;
  tableHeaderBorderColor?: HmiProperty<HmiColor>;
  tableHeaderBorderWidth?: HmiProperty<number>;
  tableHeaderBackFillStyle?: HmiProperty<number>;
  tableHeaderCornerRadius?: HmiProperty<number>;
  tableHeaderEdgeStyle?: HmiProperty<HmiLineStyle>;
  tableHeaderFirstGradientColor?: HmiProperty<HmiColor>;
  tableHeaderMiddleGradientColor?: HmiProperty<HmiColor>;
  tableHeaderSecondGradientColor?: HmiProperty<HmiColor>;
  gridLineColor?: HmiProperty<HmiColor>;
  buttonBackgroundColor?: HmiProperty<HmiColor>;
  buttonBorderBackgroundColor?: HmiProperty<HmiColor>;
  buttonBorderColor?: HmiProperty<HmiColor>;
  buttonBorderWidth?: HmiProperty<number>;
  buttonBorderStyle?: HmiProperty<HmiBorderStyle>;
  buttonWidth?: HmiProperty<number>;
  buttonBackFillStyle?: HmiProperty<number>;
  buttonCornerRadius?: HmiProperty<number>;
  buttonEdgeStyle?: HmiProperty<HmiLineStyle>;
  buttonFirstGradientColor?: HmiProperty<HmiColor>;
  buttonFirstGradientOffset?: HmiProperty<number>;
  buttonMiddleGradientColor?: HmiProperty<HmiColor>;
  buttonSecondGradientColor?: HmiProperty<HmiColor>;
  buttonSecondGradientOffset?: HmiProperty<number>;
  buttonPositions?: HmiProperty<number[]>;
  listBorderWidth?: HmiProperty<number>;
  listBorderStyle?: HmiProperty<HmiBorderStyle>;
}
