import { HmiMultilingualText } from "../../common/HmiMultilingualText.js";
import { HmiColor, HmiHorizontalAlignment, HmiImageSource, HmiProperty, HmiThickness, HmiVerticalAlignment } from "../base.js";
import { HmiWidgetBase } from "./HmiWidgetBase.js";
import { HmiButtonAction } from "./HmiButtonAction.js";
import { HmiButtonNextStateMode } from "./HmiButtonNextStateMode.js";
import { HmiButtonOperation } from "./HmiButtonOperation.js";
import { HmiButtonPressTarget } from "./HmiButtonPressTarget.js";
import { HmiHandshakeResetMode } from "./HmiHandshakeResetMode.js";
import { HmiRampDirection } from "./HmiRampDirection.js";
import { HmiState } from "./HmiState.js";
import { HmiStateTriggerMode } from "./HmiStateTriggerMode.js";
import { HmiScreenNavigationSettings } from "./HmiScreenNavigationSettings.js";
import { HmiDisabledImageMode } from "./HmiDisabledImageMode.js";
import { HmiConfirmationDialogSettings } from "./HmiConfirmationDialogSettings.js";
import { HmiButtonVisualStyle } from "./HmiButtonVisualStyle.js";
import { HmiSignatureButtonSettings } from "./HmiSignatureButtonSettings.js";
import { HmiAlarmListMode } from "../controls/HmiAlarmListMode.js";
import { HmiPasswordChangeMode } from "./HmiPasswordChangeMode.js";

export abstract class HmiButtonBase extends HmiWidgetBase {
  readonly states: HmiState[] = [];
  configuredStateCount?: HmiProperty<number>;
  stateTriggerMode?: HmiProperty<HmiStateTriggerMode>;
  state?: HmiProperty<number>;
  text?: HmiProperty<HmiMultilingualText>;
  alternateText?: HmiProperty<HmiMultilingualText>;
  navigation?: HmiScreenNavigationSettings;
  image?: HmiProperty<HmiImageSource>;
  alternateImage?: HmiProperty<HmiImageSource>;
  imageScaled?: HmiProperty<boolean>;
  imageBlink?: HmiProperty<boolean>;
  imageColor?: HmiProperty<HmiColor>;
  imageBackgroundColor?: HmiProperty<HmiColor>;
  imageBackgroundTransparent?: HmiProperty<boolean>;
  imageHorizontalAlignment?: HmiProperty<HmiHorizontalAlignment>;
  imageVerticalAlignment?: HmiProperty<HmiVerticalAlignment>;
  graphicStretchMode?: HmiProperty<number>;
  hotKey?: HmiProperty<string>;
  pressedStateTags?: HmiProperty<string>;
  styleSettings?: HmiProperty<number>;
  windowsStyle?: HmiProperty<boolean>;
  visualStyle?: HmiProperty<HmiButtonVisualStyle>;
  captureCursor?: HmiProperty<boolean>;
  highlightOnFocus?: HmiProperty<boolean>;
  downStateSameAsUp?: HmiProperty<boolean>;
  touchEnabled?: HmiProperty<boolean>;
  audioEnabled?: HmiProperty<boolean>;
  showDisabledState?: HmiProperty<boolean>;
  disabledImageMode?: HmiProperty<HmiDisabledImageMode>;
  confirmationDialog?: HmiConfirmationDialogSettings;
  signatureSettings?: HmiSignatureButtonSettings;
  autoRepeatDelaySeconds?: HmiProperty<number>;
  autoRepeatRatePerSecond?: HmiProperty<number>;
  holdTimeSeconds?: HmiProperty<number>;
  buttonAction?: HmiProperty<HmiButtonAction>;
  actionTag?: HmiProperty<string>;
  actionRemark?: HmiProperty<HmiMultilingualText>;
  buttonValue?: HmiProperty<number>;
  writeValueOnClose?: HmiProperty<boolean>;
  nextStateMode?: HmiProperty<HmiButtonNextStateMode>;
  operation?: HmiProperty<HmiButtonOperation>;
  hideUserNameEntry?: HmiProperty<boolean>;
  showDisplayOnLogout?: HmiProperty<boolean>;
  passwordChangeMode?: HmiProperty<HmiPasswordChangeMode>;
  readonly alarmFilteredTriggers: string[] = [];
  alarmPrintListMode?: HmiProperty<HmiAlarmListMode>;
  printAlarmTime?: HmiProperty<boolean>;
  printAcknowledgeTime?: HmiProperty<boolean>;
  printTriggerLabel?: HmiProperty<boolean>;
  printTriggerValue?: HmiProperty<boolean>;
  printMessage?: HmiProperty<boolean>;
  printAlarmQuantity?: HmiProperty<boolean>;
  printAccumulatedTime?: HmiProperty<boolean>;
  printAlarmState?: HmiProperty<boolean>;
  resetAlarmStatusOnClearHistory?: HmiProperty<boolean>;
  pressTarget?: HmiProperty<HmiButtonPressTarget>;
  linkedObject?: HmiProperty<string>;
  macro?: HmiProperty<string>;
  useVariableMacro?: HmiProperty<boolean>;
  targetLanguage?: HmiProperty<string>;
  rampDirection?: HmiProperty<HmiRampDirection>;
  rampIncrement?: HmiProperty<number>;
  rampLimit?: HmiProperty<number>;
  useVariableRamp?: HmiProperty<boolean>;
  useVariableLimit?: HmiProperty<boolean>;
  handshake?: HmiProperty<number>;
  latchResetMode?: HmiProperty<HmiHandshakeResetMode>;
  captionColor?: HmiProperty<HmiColor>;
  captionBackgroundColor?: HmiProperty<HmiColor>;
  touchMargin?: HmiThickness;
}
