import { HmiMultilingualText } from "../../common/HmiMultilingualText.js";
import { HmiColor, HmiHorizontalAlignment, HmiImageSource, HmiProperty, HmiThickness, HmiVerticalAlignment } from "../base.js";
import { HmiWidgetBase } from "./HmiWidgetBase.js";
import { HmiButtonAction } from "./HmiButtonAction.js";
import { HmiButtonNextStateMode } from "./HmiButtonNextStateMode.js";
import { HmiHandshakeResetMode } from "./HmiHandshakeResetMode.js";
import { HmiRampDirection } from "./HmiRampDirection.js";
import { HmiState } from "./HmiState.js";
import { HmiStateTriggerMode } from "./HmiStateTriggerMode.js";
import { HmiScreenNavigationSettings } from "./HmiScreenNavigationSettings.js";

export abstract class HmiButtonBase extends HmiWidgetBase {
  readonly states: HmiState[] = [];
  configuredStateCount?: HmiProperty<number>;
  stateTriggerMode?: HmiProperty<HmiStateTriggerMode>;
  state?: HmiProperty<number>;
  text?: HmiProperty<HmiMultilingualText>;
  alternateText?: HmiProperty<HmiMultilingualText>;
  navigation?: HmiScreenNavigationSettings;
  image?: HmiProperty<HmiImageSource>;
  alternateImage?: HmiProperty<HmiImageSource>;
  imageScaled?: HmiProperty<boolean>;
  imageBlink?: HmiProperty<boolean>;
  imageColor?: HmiProperty<HmiColor>;
  imageBackgroundColor?: HmiProperty<HmiColor>;
  imageBackgroundTransparent?: HmiProperty<boolean>;
  imageHorizontalAlignment?: HmiProperty<HmiHorizontalAlignment>;
  imageVerticalAlignment?: HmiProperty<HmiVerticalAlignment>;
  graphicStretchMode?: HmiProperty<number>;
  hotKey?: HmiProperty<string>;
  pressedStateTags?: HmiProperty<string>;
  styleSettings?: HmiProperty<number>;
  windowsStyle?: HmiProperty<boolean>;
  touchEnabled?: HmiProperty<boolean>;
  audioEnabled?: HmiProperty<boolean>;
  autoRepeatDelaySeconds?: HmiProperty<number>;
  autoRepeatRatePerSecond?: HmiProperty<number>;
  holdTimeSeconds?: HmiProperty<number>;
  buttonAction?: HmiProperty<HmiButtonAction>;
  buttonValue?: HmiProperty<number>;
  nextStateMode?: HmiProperty<HmiButtonNextStateMode>;
  rampDirection?: HmiProperty<HmiRampDirection>;
  rampIncrement?: HmiProperty<number>;
  rampLimit?: HmiProperty<number>;
  useVariableRamp?: HmiProperty<boolean>;
  useVariableLimit?: HmiProperty<boolean>;
  handshake?: HmiProperty<number>;
  latchResetMode?: HmiProperty<HmiHandshakeResetMode>;
  captionColor?: HmiProperty<HmiColor>;
  captionBackgroundColor?: HmiProperty<HmiColor>;
  touchMargin?: HmiThickness;
}
