import { HmiMultilingualText } from "../../common/HmiMultilingualText.js";
import { HmiColor, HmiFillPattern, HmiFont, HmiGradientDirection, HmiHorizontalAlignment, HmiImageSource, HmiVerticalAlignment } from "../base.js";
import { HmiDisplayParameterSource } from "./HmiDisplayParameterSource.js";

export class HmiState {
  name?: string;
  value?: number;
  text?: HmiMultilingualText;
  font?: HmiFont;
  targetDisplay?: string;
  parameterFile?: string;
  parameterList?: string;
  parameterSource?: HmiDisplayParameterSource;
  positionEnabled?: boolean;
  positionX?: number;
  positionY?: number;
  captionUsesDisplayName?: boolean;
  imageName?: string;
  image?: HmiImageSource;
  imageScaled?: boolean;
  imageColor?: HmiColor;
  imageBackgroundColor?: HmiColor;
  imageBackgroundTransparent?: boolean;
  imageHorizontalAlignment?: HmiHorizontalAlignment;
  imageVerticalAlignment?: HmiVerticalAlignment;
  captionColor?: HmiColor;
  captionBackgroundColor?: HmiColor;
  captionHorizontalAlignment?: HmiHorizontalAlignment;
  captionVerticalAlignment?: HmiVerticalAlignment;
  captionWordWrap?: boolean;
  foregroundColor?: HmiColor;
  backgroundColor?: HmiColor;
  endColor?: HmiColor;
  gradientStop?: number;
  gradientAxis?: string;
  gradientDirection?: HmiGradientDirection;
  fillPattern?: HmiFillPattern;
  patternColor?: HmiColor;
  borderColor?: HmiColor;
  blink = false;
  captionBlink = false;
  captionBackgroundTransparent?: boolean;
  imageBlink = false;
}
