// Native rectangle-gradient preview. Palettes are generated by the C# converter
// (and mirrored TS converter); this module only applies the fixed-point sampler.
// The GDI+ reference retains a known 2x backward-diagonal phase discrepancy.
export {};
const selector = "[data-hmi-bar-gradient-mode]";
const previous = new WeakMap<HTMLElement, string>();
const canvases = new WeakMap<HTMLElement, HTMLCanvasElement>();
const f = Math.fround;
const round = (value: number): number => Math.floor(f(value + 0.5));
let pending = false;

function hide(fill: HTMLElement): void {
  const canvas = canvases.get(fill);
  if (canvas && canvas.style.display !== "none") canvas.style.display = "none";
}

function update(): void {
  pending = false;
  for (const fill of document.querySelectorAll<HTMLElement>(selector)) {
    const mode = Number(fill.dataset.hmiBarGradientMode);
    if (!Number.isInteger(mode) || mode < 0 || mode > 3) { hide(fill); continue; }
    const screen = fill.closest<HTMLElement>("[data-hmi-screen]");
    if (!screen) continue;
    const root = screen.getBoundingClientRect(), rect = fill.getBoundingClientRect();
    const sx = screen.offsetWidth ? root.width / screen.offsetWidth : 1;
    const sy = screen.offsetHeight ? root.height / screen.offsetHeight : 1;
    if (!(sx > 0 && sy > 0 && rect.width > 0 && rect.height > 0)) { hide(fill); continue; }
    const dpr = window.devicePixelRatio || 1;
    const visibleLeft = Math.max(rect.left, 0), visibleTop = Math.max(rect.top, 0);
    const visibleRight = Math.min(rect.right, window.innerWidth), visibleBottom = Math.min(rect.bottom, window.innerHeight);
    if (visibleRight <= visibleLeft || visibleBottom <= visibleTop) { hide(fill); continue; }
    const pixelX = Math.floor((visibleLeft - root.left) * dpr), pixelY = Math.floor((visibleTop - root.top) * dpr);
    const width = Math.ceil((visibleRight - root.left) * dpr) - pixelX;
    const height = Math.ceil((visibleBottom - root.top) * dpr) - pixelY;
    // Bound preview allocation; no claim is made for a >16M-pixel visible bar.
    if (!(width > 0 && height > 0) || width > 32767 || height > 32767 || width * height > 16777216) { hide(fill); continue; }
    const sigma = fill.dataset.hmiBarGradientSigma === "true";
    const paletteIndex = !sigma || rect.width / sx <= 125 ? 0 : rect.width / sx <= 509 ? 1 : 2;
    const count = [16, 64, 256][paletteIndex]!;
    const text = fill.dataset.hmiBarGradientRamps ?? "";
    const key = `${mode}|${sigma}|${text}|${rect.left}|${rect.top}|${rect.width}|${rect.height}|${root.left}|${root.top}|${sx}|${sy}|${dpr}|${pixelX}|${pixelY}|${width}|${height}`;
    if (previous.get(fill) === key) continue;
    let ramps: unknown;
    try { ramps = JSON.parse(text); } catch { hide(fill); continue; }
    const palette = Array.isArray(ramps) ? ramps[paletteIndex] : undefined;
    if (!Array.isArray(palette) || palette.length !== count + 1 || !palette.every(value => Number.isInteger(value) && value >= 0 && value <= 0xffffffff)) { hide(fill); continue; }
    let canvas = canvases.get(fill);
    if (!canvas) {
      canvas = document.createElement("canvas");
      canvas.dataset.hmiBarGradientCanvas = "true";
      canvas.setAttribute("aria-hidden", "true");
      canvas.style.position = "absolute";
      canvas.style.pointerEvents = "none";
      canvas.style.imageRendering = "pixelated";
      fill.style.overflow = "hidden";
      fill.append(canvas);
      canvases.set(fill, canvas);
    }
    canvas.width = width; canvas.height = height;
    canvas.style.display = "block";
    const ox = f((rect.left - root.left) * dpr), oy = f((rect.top - root.top) * dpr);
    const rw = f(rect.width * dpr), rh = f(rect.height * dpr);
    const period = count * 65536;
    const dx = mode === 0 ? f(period / rw) : mode === 1 ? 0 : f((mode === 3 ? -period : period) / f(2 * rw));
    const dy = mode === 0 ? 0 : mode === 1 ? f(period / rh) : f(period / f(2 * rh));
    const offset = f(f((mode === 3 ? period / 2 : 0) - f(ox * dx)) - f(oy * dy));
    const ix = round(dx), iy = round(dy), io = round(offset);
    const context = canvas.getContext("2d");
    if (!context) { hide(fill); continue; }
    const image = context.createImageData(width, height);
    for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
      const position = ix * (pixelX + x) + iy * (pixelY + y) + io;
      const amount = Math.floor(((position % period + period) % period) / 256);
      const slot = amount >> 8, fraction = (amount & 255) / 256;
      const start = palette[slot]!, end = palette[slot + 1]!;
      const mix = (shift: number): number => round(f(f((start >>> shift & 255) * f(1 - fraction)) + f((end >>> shift & 255) * fraction)));
      const alpha = mix(24), pixel = (y * width + x) * 4;
      // Reconstruct straight bytes that preserve the verified premultiplied
      // bytes in Canvas, rather than recycling GDI+ GetPixel's truncated RGB.
      if (alpha) for (let channel = 0; channel < 3; channel++) image.data[pixel + channel] = Math.round(mix(16 - channel * 8) * 255 / alpha);
      image.data[pixel + 3] = alpha;
    }
    context.putImageData(image, 0, 0);
    canvas.style.left = `${(pixelX - ox) / (dpr * sx)}px`;
    canvas.style.top = `${(pixelY - oy) / (dpr * sy)}px`;
    canvas.style.width = `${width / (dpr * sx)}px`;
    canvas.style.height = `${height / (dpr * sy)}px`;
    previous.set(fill, key);
  }
}

function schedule(): void { if (!pending) { pending = true; requestAnimationFrame(update); } }
const sizes = new ResizeObserver(schedule);
function observe(): void {
  sizes.disconnect();
  for (const element of document.querySelectorAll(`${selector},[data-hmi-screen]`)) sizes.observe(element);
  schedule();
}
new MutationObserver(records => { if (records.some(record => record.type === "childList")) observe(); else schedule(); }).observe(document.documentElement,
  { subtree: true, childList: true, attributes: true, attributeFilter: ["style", "class", "data-hmi-bar-gradient-mode", "data-hmi-bar-gradient-sigma", "data-hmi-bar-gradient-ramps"] });
window.addEventListener("resize", schedule);
document.addEventListener("scroll", schedule, true);
function watchDensity(): void {
  matchMedia(`(resolution: ${window.devicePixelRatio || 1}dppx)`).addEventListener("change", () => { schedule(); watchDensity(); }, { once: true });
}
watchDensity(); observe();
