namespace BaseHmiTypes.Screens.Base;

public enum HmiFillPattern
{
    Transparent,
    Solid,
    DiagonalLeftToRight,
    Checkers,
    DiagonalCross,
    DiagonalRightToLeft,
    Horizontal,
    Vertical,
    DottedHorizontal,
    DottedEvenOdd,
    DottedEvenOddFiner,
    DiagonalCrossFiner,
    DottedEvenOddFinest,
    HorizontalDifferentLines,
    CheckersFiner,
    DiagonalCrossBold,
    DottedHorizontalInverted,
    Bricks,
    BricksDiagonal,
    Diagonal,
    Dots,
    SmallBoxes,
    MediumBoxes,
    LargeBoxes,
    WideVertical,
    WideHorizontal,
    WideDiagonalRightToLeft,
    WideDiagonalLeftToRight,
    Ovals,
    Diamonds,
    Scales,
    Waves
}
