// <auto-generated />
import { HmiScriptLanguage } from "../../screens/base/HmiProperty.js";
import { HmiScriptCommand } from "../HmiScriptCommand.js";
import { HmiScriptCommandCatalog } from "../HmiScriptCommandCatalog.js";
import { HmiScriptCommandDefinition, HmiScriptCommandParameterDefinition } from "../HmiScriptCommandDefinition.js";
import * as AdvancedCommands from "./HmiAdvancedScriptCommands.generated.js";

type AdvancedCommandConstructor = {
  readonly key: string;
  readonly name: string;
  new (): HmiScriptCommand;
};

export class HmiAdvancedScriptCommandCatalog extends HmiScriptCommandCatalog {
  static readonly instance = new HmiAdvancedScriptCommandCatalog();

  private constructor() {
    super(createDefinitions());
  }
}

function createDefinitions(): HmiScriptCommandDefinition[] {
  return Object.values(AdvancedCommands)
    .filter(isCommandConstructor)
    .map((commandType) => {
      const command = new commandType();
      const definition = new HmiScriptCommandDefinition();
      definition.key = command.commandKey;
      definition.name = command.commandName;
      definition.displayName = command.commandName;
      definition.language = HmiScriptLanguage.C;
      definition.commandType = commandType;
      for (const argument of command.arguments) {
        const parameter = new HmiScriptCommandParameterDefinition();
        parameter.name = argument.parameterName;
        parameter.propertyName = argument.propertyName;
        parameter.direction = argument.direction;
        definition.parameters.push(parameter);
      }

      return definition;
    });
}

function isCommandConstructor(value: unknown): value is AdvancedCommandConstructor {
  return typeof value === "function" && "key" in value && "name" in value;
}
