// <auto-generated />
namespace BaseHmiTypes.Converters.Html;

internal static class HmiHtmlCommonStyle
{
    internal static readonly string Style = "*,*::before,*::after{box-sizing:border-box;}";
}
