export enum HmiProjectItemKind {
  Unknown = "Unknown",
  Screen = "Screen",
  TagTable = "TagTable",
  Tag = "Tag",
  Script = "Script",
  TextList = "TextList",
  GraphicList = "GraphicList",
  Image = "Image",
  Cycle = "Cycle",
  AlarmList = "AlarmList",
  ConnectionList = "ConnectionList",
  Faceplate = "Faceplate",
  Recipe = "Recipe",
}
