import assert from "node:assert/strict";
import test from "node:test";
import { HmiAlarmControl, HmiAlarmColumnSet, HmiAlarmColumn, HmiScreen, HmiLayer, HmiScreenToHtmlConverter, staticProperty, hmiColorFromArgb } from "../dist/index.js";
test("Grid dimensions stay optional and unknown modes use legacy preview flags", async () => {
  const control = Object.assign(new HmiAlarmControl(), { defaultColumnSet: "Primary", showHorizontalGridLines: staticProperty(false), showVerticalGridLines: staticProperty(true), gridLineWidth: staticProperty(2.5), cellPaddingLeft: staticProperty(19), cellPaddingRight: staticProperty(99) });
  const set = Object.assign(new HmiAlarmColumnSet(), { name: "Primary", gridLineColor: staticProperty(hmiColorFromArgb(0, 17, 34, 51)), gridLineWidth: staticProperty(0), gridLineVisibility: staticProperty(2), cellPaddingLeft: staticProperty(0), cellPaddingTop: staticProperty(7), cellPaddingRight: staticProperty(-7), rowHeight: staticProperty(0) }); control.columnSets.push(set); set.columns.push(Object.assign(new HmiAlarmColumn(), { sourceType: "Column" }));
  const screen = new HmiScreen(), layer = new HmiLayer(); screen.layers.push(layer); layer.items.push(control); const renderer = new HmiScreenToHtmlConverter();
  const table = html => html.split('<table class="hmi-alarm-table')[1].split("</table>")[0], body = html => table(html).split("<tbody>")[1];
  let html = await renderer.convertAsync(screen), content = body(html); for (const fragment of ['border-width: 0px 0px;', 'border-color: rgba(17,34,51,0);', 'padding-left: 0px;', 'padding-top: 7px;', 'height: auto;']) assert.ok(content.includes(fragment), fragment);
  assert.ok(!content.includes('padding-right: -7px')); assert.ok(!content.includes('padding-right: 99px')); assert.ok(html.includes('data-view-cell-padding-right="-7"'));
  set.gridLineVisibility = staticProperty(3); delete set.gridLineWidth; set.rowHeight = staticProperty(12.5); content = body(await renderer.convertAsync(screen)); assert.ok(content.includes('border-width: 0px 2.5px;')); assert.ok(content.includes('height: 12.5px;'));
  for (const invalid of [NaN, Infinity, -1]) { set.gridLineWidth = staticProperty(invalid); set.rowHeight = staticProperty(invalid); set.cellPaddingTop = staticProperty(invalid); content = body(await renderer.convertAsync(screen)); assert.ok(content.includes('border-width: 0px 2.5px;')); assert.ok(!content.includes('height:')); assert.ok(!content.includes('padding-top:')); }
  set.gridLineWidth = staticProperty(4); delete set.rowHeight; delete set.cellPaddingLeft; set.gridLineVisibility = staticProperty(1); control.showHeader = staticProperty(false); html = await renderer.convertAsync(screen); content = body(html); assert.ok(content.includes('border-width: 0px 4px;')); assert.ok(content.includes('padding-left: 19px;')); assert.ok(!table(html).includes("<thead>")); assert.ok(html.includes('data-view-grid-line-visibility="1"'));
  set.columns.length = 0; set.gridLineVisibility = staticProperty(0); content = body(await renderer.convertAsync(screen)); assert.ok(content.includes('border-width: 0px 0px;')); assert.ok(content.includes('Alarm data not loaded'));
  control.activeColumnSet = "Unknown"; content = body(await renderer.convertAsync(screen)); assert.ok(content.includes('border-width: 0px 2.5px;')); assert.ok(!content.includes('rgba(17,34,51,0)'));
});
