import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]);for(const [at,v] of [[0,1],[4,88],[16,39],[20,39],[40,0x464d4520],[44,0x10000],[48,b.length],[52,records.length+2]])b.writeUInt32LE(v,at);b.writeUInt16LE(2,56);return b;}
function wrecord(type,...values){const b=Buffer.alloc(6+values.length*2);b.writeUInt32LE(b.length/2);b.writeUInt16LE(type,4);values.forEach((v,i)=>b.writeInt16LE(v,6+i*2));return b;}
function wmf(...records){const b=Buffer.concat([Buffer.alloc(18),...records,wrecord(0)]);b.writeUInt16LE(1);b.writeUInt16LE(9,2);b.writeUInt16LE(0x300,4);b.writeUInt32LE(b.length/2,6);b.writeUInt16LE(2,10);b.writeUInt32LE(Math.max(3,...records.map(r=>r.length/2)),12);return b;}
const region=(mode=5,rects=[[5,6,35,36]])=>record(75,32+rects.length*16,mode,32,1,rects.length,rects.length*16,0,0,39,39,...rects.flat());
function polygon(){const b=Buffer.alloc(52);b.writeUInt32LE(3);b.writeUInt32LE(52,4);b.writeUInt32LE(3,24);[5,5,35,5,20,35].forEach((v,i)=>b.writeInt32LE(v,28+i*4));return b;}
const render=(b,w=false)=>new MetafileToSvgRenderer().render(b,w?'.wmf':'.emf'),svg=(...r)=>render(emf(...r));
const attrs=tag=>Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const drawing=s=>attrs([...s.replace(/<defs>[^]*?<\/defs>/,'').matchAll(/<(?:path|rect|line)\b[^>]*>/g)].at(-1)[0]);
const masks=s=>[...s.matchAll(/(<mask\b[^>]*>)([^]*?)<\/mask>/g)].map(m=>({...attrs(m[1]),body:m[2]})),lastMask=s=>masks(s).at(-1),transform=m=>attrs(m.body.match(/<g\b[^>]*>/)[0]).transform;
const bits=f=>{const b=Buffer.alloc(4);b.writeFloatLE(f);return b.readUInt32LE();};
for(const w of [false,true])for(const mask of [false,true])test(`Offset EMF/WMF clip or mask: ${w}/${mask}`,()=>{const s=w?render(wmf(wrecord(0x20c,40,40),wrecord(mask?0x415:0x416,35,35,5,5),wrecord(0x220,-5,10),wrecord(0x41b,39,39,0,0)),true):svg(record(mask?29:30,5,5,35,35),record(26,10,-5),record(43,0,0,39,39)),m=lastMask(s);assert.equal(drawing(s).mask,'url(#mask2)');assert.equal(transform(m),'translate(10 -5)');assert.equal(attrs(m.body.match(/<rect\b[^>]*>/)[0])[mask?'mask':'clip-path'],mask?'url(#mask1)':'url(#clip1)');});
for(const w of [false,true])test(`Offset without clip leaves default unchanged: ${w}`,()=>{const s=w?render(wmf(wrecord(0x220,2,1),wrecord(0x213,20,39)),true):svg(record(26,1,2),record(54,39,20));assert.equal(masks(s).length,0);assert.equal(drawing(s).mask,undefined);});
for(const mask of [false,true])test(`Zero clip offset retains definition: ${mask}`,()=>assert.equal(drawing(svg(record(mask?29:30,5,5,35,35),record(26,0,0),record(43,0,0,39,39)))[mask?'mask':'clip-path'],mask?'url(#mask1)':'url(#clip1)'));
for(const [variant,expected] of [[0,'translate(10 -5)'],[1,'translate(20 -15)'],[2,'translate(5 10)'],[3,'translate(20 -15)'],[4,'translate(10 30)']])test(`Offset vector mapping in native order: ${variant}`,()=>{const r=[region()];if(variant===1)r.push(record(35,bits(2),0,0,bits(3),bits(10),bits(20)));if(variant===2||variant===4)r.push(record(35,0,bits(1),bits(-1),0,bits(40),0));if(variant>=3)r.push(record(9,10,10),record(11,20,30),record(10,3,4),record(12,10,20));r.push(record(26,10,-5));assert.equal(transform(lastMask(svg(...r))),expected);});
test('Huge world translation does not cancel small offset',()=>assert.equal(transform(lastMask(svg(region(),record(35,bits(1),0,0,bits(1),0x7f7fffff,0x7f7fffff),record(26,1,2)))),'translate(1 2)'));
test('Offset does not move DC point',()=>{const a=drawing(svg(record(27,1,2),region(),record(26,10,-5),record(54,8,9)));assert.equal(a.x1,'1');assert.equal(a.y1,'2');});
for(const open of [false,true])test(`Offset retains selected/open path: ${open}`,()=>{const r=[region(),record(59),polygon()];if(!open)r.push(record(60));r.push(record(26,10,-5));if(open)r.push(record(60));r.push(record(64,0,0,39,39));assert.equal(drawing(svg(...r)).d,'M 5 5 L 35 5 L 20 35 Z');});
for(const mask of [false,true])test(`SaveRestore returns unmoved clip/mask: ${mask}`,()=>assert.equal(drawing(svg(record(mask?29:30,5,5,35,35),record(33),record(26,10,-5),record(34,-1),record(43,0,0,39,39)))[mask?'mask':'clip-path'],mask?'url(#mask1)':'url(#clip1)'));
test('Subsequent clip combination references moved mask',()=>{const s=svg(region(),record(26,10,-5),record(30,0,0,39,39),record(43,0,0,39,39));assert.equal(drawing(s).mask,'url(#mask3)');assert.ok(lastMask(s).body.includes('mask="url(#mask2)"'));});
for(const w of [false,true])for(const count of [0,1])test(`Truncated EMF/WMF clip offset: ${w}/${count}`,()=>{const s=w?render(wmf(wrecord(0x416,35,35,5,5),wrecord(0x220,...Array(count).fill(5)),wrecord(0x41b,39,39,0,0)),true):svg(region(),record(26,...Array(count).fill(5)),record(43,0,0,39,39));assert.equal(drawing(s)['clip-path'],'url(#clip1)');assert.equal(masks(s).length,0);});
for(const value of [0x7fc00000,0x7f800000])test(`Nonfinite mapped offset leaves clip: ${value}`,()=>assert.equal(masks(svg(region(),record(35,value,0,0,bits(1),0,0),record(26,1,2))).length,0));
test('Mask domain retains outside geometry moved into viewport',()=>{const s=svg(region(5,[[45,5,65,35]]),region(1,[[45,5,65,35]]),record(26,-40,0));for(const m of masks(s)){assert.equal(m.x,'-40');assert.equal(m.width,'120');}assert.ok(!s.includes('__METAFILE_'));});
test('Captured default region stays finite while resources expand',()=>{const s=svg(record(29,5,5,35,35),record(26,10,0)),m=masks(s)[0],previous=attrs(m.body.match(/<rect\b[^>]*>/)[0]);assert.equal(m.width,'60');assert.equal(previous.x,'0');assert.equal(previous.width,'40');});
test('Domain covers nonchronological SaveRestore offset chains',()=>{const rects=[[-95,5,-65,35]],s=svg(region(5,rects),region(1,rects),record(33),record(26,-50,0),record(34,-1),record(26,50,0),record(33),record(26,-50,0),record(34,-1),record(26,50,0));assert.equal(masks(s)[0].width,'440');assert.equal(lastMask(s).x,'-200');});
test('Empty region remains selected after offset',()=>assert.equal(drawing(svg(region(5,[]),record(26,10,0),record(43,0,0,39,39))).mask,'url(#mask2)'));
test('Signed extreme offsets do not overflow mask domain',()=>{const m=lastMask(svg(region(),record(26,-2147483648,2147483647)));assert.equal(m.x,'-2147483648');assert.equal(m.width,'4294967336');});
for(const w of [false,true])for(const mask of [false,true])test(`HTML offset source preservation: ${w}/${mask}`,async()=>{const b=w?wmf(wrecord(0x20c,40,40),wrecord(mask?0x415:0x416,35,35,5,5),wrecord(0x220,-5,10),wrecord(0x41b,39,39,0,0)):emf(record(mask?29:30,5,5,35,35),record(26,10,-5),record(43,0,0,39,39)),original=Buffer.from(b),uri='data:image/'+(w?'wmf':'emf')+';base64,'+b.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Offset',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.equal(drawing(decodeURIComponent(match[1])).mask,'url(#mask2)');assert.equal(item.source.staticValue,uri);assert.deepEqual(b,original);});
