import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]);for(const [at,v] of [[0,1],[4,88],[16,39],[20,39],[40,0x464d4520],[44,0x10000],[48,b.length],[52,records.length+2]])b.writeUInt32LE(v,at);b.writeUInt16LE(2,56);return b;}
const region=(mode=5,rects=[[5,6,35,36]])=>record(75,32+rects.length*16,mode,32,1,rects.length,rects.length*16,0,0,39,39,...rects.flat());
const points=()=>record(3,0,0,39,39,3,5,5,35,5,20,35),paint=()=>record(43,0,0,39,39);
const svg=(...r)=>new MetafileToSvgRenderer().render(emf(...r),'.emf');
const attrs=tag=>Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const body=s=>s.replace(/<defs>[^]*?<\/defs>/,'').replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,''),opening=s=>body(s).match(/^<[^>]*>/)[0],draw=s=>body(s).match(/<(?:rect|line|path|ellipse|polygon)\b[^>]*>/)[0];
const masks=s=>[...s.matchAll(/<mask\b([^>]*)>([^]*?)<\/mask>/g)].map(m=>({...attrs(m[1]),body:m[2]})),mask=(s,id)=>masks(s).find(m=>m.id===id);
for(const isMask of [false,true])test(`Capture selected clip/mask and clear selection: ${isMask}`,()=>{const s=svg(record(isMask?29:30,5,5,25,35),record(28),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.equal(attrs(draw(s)).mask,undefined);assert.equal(attrs(draw(s))['clip-path'],undefined);assert.equal(attrs(mask(s,'mask2').body.match(/<rect[^>]*>/)[0])[isMask?'mask':'clip-path'],isMask?'url(#mask1)':'url(#clip1)');});
test('No selected clip does not create meta region',()=>{const s=svg(record(28),paint());assert.ok(opening(s).startsWith('<rect'));assert.equal(masks(s).length,0);});
test('Repeated meta without selection retains definition',()=>{const s=svg(region(),record(28),record(28),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.equal(masks(s).length,1);});
test('Offset without new selection does not move meta',()=>{const s=svg(region(),record(28),record(26,10,0),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.ok(!s.includes('transform='));});
test('Null COPY does not clear meta',()=>assert.equal(attrs(opening(svg(region(),record(28),record(75,0,5),paint()))).mask,'url(#mask2)'));
for(const mode of [1,2,3,4,5])test(`New selection independently constrained: ${mode}`,()=>{const s=svg(region(),record(28),region(mode,[[15,5,35,35]]),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.ok(attrs(draw(s))[mode===1||mode===5?'clip-path':'mask']);});
test('Repeated meta intersects prior meta and new selection',()=>{const s=svg(region(),record(28),region(),record(28),paint()),m=mask(s,'mask4');assert.equal(attrs(opening(s)).mask,'url(#mask4)');assert.equal(attrs(m.body.match(/<g[^>]*>/)[0]).mask,'url(#mask2)');assert.equal(attrs(m.body.match(/<rect[^>]*>/)[0])['clip-path'],'url(#clip3)');});
test('Empty selection produces empty meta',()=>{const s=svg(region(5,[]),record(28),record(75,0,5),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.equal(attrs(s.match(/<path[^>]*>/)[0]).d,'');});
test('Restore before meta removes meta',()=>{const s=svg(record(33),region(),record(28),record(34,-1),paint());assert.ok(opening(s).startsWith('<rect'));assert.equal(attrs(opening(s)).mask,undefined);});
test('Restore retains prior meta and selected clip',()=>{const s=svg(region(),record(28),region(),record(33),record(28),record(34,-1),paint());assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.equal(attrs(draw(s))['clip-path'],'url(#clip3)');});
test('Meta does not move DC point',()=>{const s=svg(record(27,1,2),region(),record(28),record(54,8,9)),a=attrs(draw(s));assert.equal(a.x1,'1');assert.equal(a.y1,'2');});
for(const open of [false,true])test(`Meta retains selected/open path: ${open}`,()=>{const r=[region(),record(59),points()];if(!open)r.push(record(60));r.push(record(28));if(open)r.push(record(60));r.push(record(64,0,0,39,39));assert.equal(attrs(draw(svg(...r))).d,'M 5 5 L 35 5 L 20 35 Z');});
for(const kind of [0,1,2,3,4])test(`Meta wraps existing drawing families: ${kind}`,()=>{const r=kind===0?[paint()]:kind===1?[record(42,0,0,39,39)]:kind===2?[record(54,39,20)]:kind===3?[points()]:[record(59),points(),record(60),record(64,0,0,39,39)],s=svg(region(),record(28),...r);assert.equal(attrs(opening(s)).mask,'url(#mask2)');assert.equal([...body(s).matchAll(/<(?:rect|line|path|ellipse|polygon)\b/g)].length,1);});
for(const isMask of [false,true])test(`HTML meta region source preservation: ${isMask}`,async()=>{const b=emf(record(isMask?29:30,5,5,25,35),record(28),paint()),original=Buffer.from(b),uri='data:image/emf;base64,'+b.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Meta',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.equal(attrs(opening(decodeURIComponent(match[1]))).mask,'url(#mask2)');assert.equal(item.source.staticValue,uri);assert.deepEqual(b,original);});
