import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]);for(const [at,v] of [[0,1],[4,88],[16,39],[20,39],[40,0x464d4520],[44,0x10000],[48,b.length],[52,records.length+2]])b.writeUInt32LE(v,at);b.writeUInt16LE(2,56);return b;}
function points(type,coords=[5,5,35,5,20,35]){const short=type===86||type===87,b=Buffer.alloc(28+coords.length*(short?2:4));b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);b.writeUInt32LE(coords.length/2,24);coords.forEach((v,i)=>short?b.writeInt16LE(v,28+i*2):b.writeInt32LE(v,28+i*4));return b;}
const box=(l,r)=>points(3,[l,5,r,5,r,35,l,35]),clip=(l,r,mode=5)=>[record(59),box(l,r),record(60),record(67,mode)];
const render=(...records)=>new MetafileToSvgRenderer().render(emf(...records),'.emf');
const attrs=tag=>Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const last=svg=>attrs([...svg.matchAll(/<(?:rect|line|polygon|polyline|path|ellipse)\b[^>]*>/g)].at(-1)[0]);
for(const [mode,expected] of [[1,'evenodd'],[2,'nonzero']])test(`Clip fill rule evaluated at selection: ${mode}`,()=>{const svg=render(record(19,3-mode),record(59),box(5,35),box(12,28),record(60),record(19,mode),record(67,5)),a=last(svg);assert.equal(a['clip-rule'],expected);assert.equal(a['fill-rule'],expected);});
for(const mode of [1,2,3,4,5])test(`Clip combination mode: ${mode}`,()=>{const svg=render(...clip(5,25),...clip(15,35,mode),record(43,0,0,39,39)),a=last(svg);assert.equal(a['clip-path'],mode===5?'url(#clip2)':undefined);assert.equal(a.mask,mode===5?undefined:'url(#mask2)');if(mode!==5){const m=attrs(svg.match(/<mask\b[^>]*>/)[0]);assert.equal(m.maskUnits,'userSpaceOnUse');assert.equal(m.width,'40');assert.match(svg,/<mask[^]*clip-path="url\(#clip1\)"/);}});
for(const type of [54,3,4,86,87,43,42,44,45])test(`Existing primitive respects clipping: ${type}`,()=>{const drawing=[3,4,86,87].includes(type)?points(type):type===44?record(type,0,0,39,39,10,10):type===45?record(type,0,0,39,39,39,20,20,0):type===54?record(type,39,20):record(type,0,0,39,39);for(const mask of [false,true]){const a=last(render(...clip(5,25),...(mask?clip(15,35,1):[]),drawing));assert.equal(a[mask?'mask':'clip-path'],mask?'url(#mask2)':'url(#clip1)');}});
for(const mode of [1,2,3,4,5])test(`Clip combination without previous clip: ${mode}`,()=>{const a=last(render(...clip(15,35,mode),record(43,0,0,39,39))),simple=mode===1||mode===5;assert.equal(a[simple?'clip-path':'mask'],simple?'url(#clip1)':'url(#mask1)');});
for(const mode of [0,6,-1,-2147483648])test(`Invalid clip mode retains selected path: ${mode}`,()=>{const svg=render(...clip(5,25),record(59),box(15,35),record(60),mode===-2147483648?record(67):record(67,mode),record(64,0,0,39,39));assert.equal([...svg.matchAll(/<clipPath\b/g)].length,1);assert.equal(last(svg)['clip-path'],'url(#clip1)');});
for(const mode of [1,5])test(`Empty path retains previous clip: ${mode}`,()=>assert.equal(last(render(...clip(5,25),record(59),record(60),record(67,mode),record(43,0,0,39,39)))['clip-path'],'url(#clip1)'));
for(const mask of [false,true])test(`SaveRestore restores clip or mask: ${mask}`,()=>{const a=last(render(...clip(5,25),...(mask?clip(15,35,1):[]),record(33),...clip(1,10),record(34,-1),record(43,0,0,39,39)));assert.equal(a[mask?'mask':'clip-path'],mask?'url(#mask2)':'url(#clip1)');});
test('Copy replaces combined mask',()=>{const a=last(render(...clip(5,25),...clip(15,35,1),...clip(1,10),record(43,0,0,39,39)));assert.equal(a['clip-path'],'url(#clip3)');assert.equal(a.mask,undefined);});
for(const mask of [false,true])test(`SaveRestore returns to unclipped state: ${mask}`,()=>{const a=last(render(record(33),...clip(5,25),...(mask?clip(15,35,1):[]),record(34,-1),record(43,0,0,39,39)));assert.equal(a['clip-path'],undefined);assert.equal(a.mask,undefined);});
test('Valid selection consumes finished path',()=>{const svg=render(...clip(5,25),record(64,0,0,39,39),record(43,0,0,39,39)).replace(/<defs>[^]*?<\/defs>/,'');assert.equal([...svg.matchAll(/<(?:path|rect)\b/g)].length,1);});
for(const mode of [1,2])test(`HTML combined clipping preserves source: ${mode}`,async()=>{const bytes=emf(...clip(5,25),record(19,mode),...clip(15,35,3),record(43,0,0,39,39)),original=Buffer.from(bytes),uri='data:image/emf;base64,'+bytes.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Clip',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.equal([...decodeURIComponent(match[1]).matchAll(/<mask\b/g)].length,1);assert.equal(item.source.staticValue,uri);assert.deepEqual(bytes,original);});
