import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]),u=(at,v)=>b.writeUInt32LE(v,at);u(0,1);u(4,88);u(16,39);u(20,39);u(40,0x464d4520);u(44,0x10000);u(48,b.length);u(52,records.length+2);b.writeUInt16LE(2,56);return b;}
function points(type,coordinates){const short=type>=85,size=short?2:4,b=Buffer.alloc(28+coordinates.length*size);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);b.writeUInt32LE(coordinates.length/2,24);coordinates.forEach((v,i)=>short?b.writeInt16LE(v,28+i*size):b.writeInt32LE(v,28+i*size));return b;}
function polyDraw(type,types,coordinates){const original=points(type,coordinates),b=Buffer.alloc((original.length+types.length+3)&~3);original.copy(b);Buffer.from(types).copy(b,original.length);b.writeUInt32LE(b.length,4);return b;}
const svg=(...records)=>new MetafileToSvgRenderer().render(emf(...records),'.emf');
const elements=(...records)=>[...svg(...records).matchAll(/<(path|line)\b([^>]+)>/g)].map(m=>({tag:m[1],...Object.fromEntries([...m[2].matchAll(/([\w-]+)="([^"]*)"/g)].map(a=>[a[1],a[2]]))}));
const path=(...records)=>elements(...records).find(e=>e.tag==='path').d;
const open=()=>[record(59),record(27,5,5),record(54,35,5),record(54,35,35)],paint=()=>[record(60),record(64,0,0,39,39)];
for(const coincident of [false,true])test(`Close preserves endpoint and starts new figure: ${coincident}`,()=>{const r=open();if(coincident)r.push(record(54,5,5));r.push(record(61),record(54,5,35),...paint());assert.ok(path(...r).endsWith(coincident?'Z M 5 5 L 5 35':'Z M 35 35 L 5 35'));});
test('Repeated CloseFigure adds no geometry',()=>assert.equal(path(...open(),record(61),record(61),record(54,5,35),...paint()),'M 5 5 L 35 5 L 35 35 Z M 35 35 L 5 35'));
for(const move of [false,true])test(`Empty and move-only CloseFigure produces no geometry: ${move}`,()=>assert.equal(elements(record(59),...(move?[record(27,5,5)]:[]),record(61),record(61),...paint()).length,0));
for(const previousClosed of [false,true])test(`Closing pending move closes previous drawn figure: ${previousClosed}`,()=>{const r=open();if(previousClosed)r.push(record(61));r.push(record(27,8,8),record(61),record(61),record(54,12,12),...paint());assert.equal(path(...r),'M 5 5 L 35 5 L 35 35 Z M 8 8 L 12 12');});
for(const state of [0,1,2])test(`Close outside construction leaves DC position unchanged: ${state}`,()=>{const r=state?[...open(),record(state===1?60:68)]:[record(27,35,35)];r.push(record(61),record(54,5,35));const line=elements(...r).find(e=>e.tag==='line');assert.equal(line.x1,'35');assert.equal(line.y1,'35');});
for(const [type,x,y] of [[3,5,5],[86,5,5],[43,35,5],[42,35,20]])test(`Already-closed independent shape starts new figure: ${type}`,()=>{const shape=type===3||type===86?points(type,[5,5,35,5,20,35]):record(type,5,5,35,35),d=path(record(27,x,y),record(59),shape,record(61),record(54,5,35),...paint());assert.ok(d.endsWith(`Z M ${x} ${y} L 5 35`));assert.equal([...d.matchAll(/Z/g)].length,1);});
for(const type of [5,88,6,89])test(`Curve or polyline-to after close starts at endpoint: ${type}`,()=>{const line=type===6||type===89,curve=points(type,line?[15,10,35,30]:[5,0,35,0,35,30]);assert.ok(path(...open(),record(61),curve,...paint()).includes('Z M 35 35 '+(line?'L':'C')));});
for(const type of [56,92])for(const active of [false,true])test(`PolyDraw close within one record starts new figure: ${type}/${active}`,()=>assert.equal(path(...(active?[record(59)]:[]),polyDraw(type,[6,2,3,2],[5,5,35,5,5,5,5,35]),...(active?paint():[])),'M 5 5 L 35 5 L 5 5 Z M 5 5 L 5 35'));
for(const type of [56,92])test(`Separate PolyDraw after closed figure starts new figure: ${type}`,()=>assert.equal(path(record(59),polyDraw(type,[6,2,3],[5,5,35,5,5,5]),polyDraw(type,[2],[5,35]),...paint()),'M 5 5 L 35 5 L 5 5 Z M 5 5 L 5 35'));
test('Move reopens after closed figure',()=>assert.ok(path(...open(),record(61),record(27,8,8),record(54,12,12),...paint()).endsWith('Z M 8 8 L 12 12')));
for(const closed of [false,true])test(`SaveDC/RestoreDC preserves open or closed figure: ${closed}`,()=>{const r=open();if(closed)r.push(record(61));r.push(record(33));if(!closed)r.push(record(61));r.push(record(27,8,8),record(54,12,12),record(34,-1),record(54,5,35),...paint());assert.equal(path(...r),'M 5 5 L 35 5 L 35 35'+(closed?' Z M 35 35':'')+' L 5 35');});
test('Mapping preserves closed endpoint continuity',()=>assert.ok(path(record(17,8),record(9,10,10),record(11,20,30),record(12,4,7),...open(),record(61),record(54,5,35),...paint()).endsWith('Z M 74 112 L 14 112')));
for(const coincident of [false,true])test(`HTML renders new figure without source mutation: ${coincident}`,async()=>{const r=open();if(coincident)r.push(record(54,5,5));r.push(record(61),record(54,5,35),...paint());const bytes=emf(...r),original=Buffer.from(bytes),uri='data:image/emf;base64,'+bytes.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Closed',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.ok(decodeURIComponent(match[1]).includes(coincident?'Z M 5 5 L 5 35':'Z M 35 35 L 5 35'));assert.equal(item.source.staticValue,uri);assert.deepEqual(bytes,original);});
