import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]);for(const [at,v] of [[0,1],[4,88],[16,39],[20,39],[40,0x464d4520],[44,0x10000],[48,b.length],[52,records.length+2]])b.writeUInt32LE(v,at);b.writeUInt16LE(2,56);return b;}
const region=(mode=5,rects=[[5,6,35,36]])=>record(75,32+rects.length*16,mode,32,1,rects.length,rects.length*16,0,0,39,39,...rects.flat());
const change=(r,at,v)=>{const b=Buffer.from(r);b.writeUInt32LE(v>>>0,at);return b;};
function polygon(){const b=Buffer.alloc(52);b.writeUInt32LE(3);b.writeUInt32LE(52,4);b.writeUInt32LE(3,24);[5,5,35,5,20,35].forEach((v,i)=>b.writeInt32LE(v,28+i*4));return b;}
const svg=(...r)=>new MetafileToSvgRenderer().render(emf(...r),'.emf');
const attrs=tag=>Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const geometry=s=>attrs(s.match(/<path\b[^>]*>/)[0]),drawing=s=>attrs([...s.replace(/<defs>[^]*?<\/defs>/,'').matchAll(/<(?:path|rect|line)\b[^>]*>/g)].at(-1)[0]);
const bits=f=>{const b=Buffer.alloc(4);b.writeFloatLE(f);return b.readUInt32LE();};
test('Compound rectangles use nonzero region union',()=>{const s=svg(record(19,1),region(5,[[5,5,15,35],[25,5,35,35]]),record(43,0,0,39,39));assert.equal(geometry(s).d,'M 5 5 L 15 5 L 15 35 L 5 35 Z M 25 5 L 35 5 L 35 35 L 25 35 Z');assert.equal(geometry(s)['clip-rule'],'nonzero');assert.equal(drawing(s)['clip-path'],'url(#clip1)');});
for(const mode of [1,2,3,4,5])test(`Extended region combination: ${mode}`,()=>{const a=drawing(svg(region(5,[[5,5,25,35]]),region(mode,[[15,5,35,35]]),record(43,0,0,39,39)));assert.equal(a[mode===5?'clip-path':'mask'],mode===5?'url(#clip2)':'url(#mask2)');});
for(const mode of [1,2,3,4,5])test(`Empty region does not reset: ${mode}`,()=>{const s=svg(region(),region(mode,[]),record(43,0,0,39,39));assert.equal(drawing(s)[mode===5?'clip-path':'mask'],mode===5?'url(#clip2)':'url(#mask2)');assert.equal(attrs([...s.matchAll(/<path\b[^>]*>/g)].at(-1)[0]).d,'');});
for(const mask of [false,true])test(`Null COPY resets clip and mask: ${mask}`,()=>{const a=drawing(svg(region(),...(mask?[region(4)]:[]),record(75,0,5),record(43,0,0,39,39)));assert.equal(a['clip-path'],undefined);assert.equal(a.mask,undefined);});
for(const mode of [0,1,2,3,4,6])test(`Invalid null region mode leaves clip: ${mode}`,()=>assert.equal(drawing(svg(region(),record(75,0,mode),record(43,0,0,39,39)))['clip-path'],'url(#clip1)'));
for(const world of [false,true])test(`Serialized region ignores world/window mapping: ${world}`,()=>{const r=world?[record(35,bits(2),0,0,bits(3),bits(10),bits(20)),region()]:[record(17,8),record(9,10,10),record(11,20,30),record(12,4,7),region()];assert.equal(geometry(svg(...r)).d,'M 5 6 L 35 6 L 35 36 L 5 36 Z');});
test('Region Bounds are not substituted for rectangles',()=>assert.equal(geometry(svg(change(region(),32,-2147483648))).d,'M 5 6 L 35 6 L 35 36 L 5 36 Z'));
test('Zero unknown rectangle buffer size is accepted',()=>assert.equal(drawing(svg(change(region(),28,0),record(43,0,0,39,39)))['clip-path'],'url(#clip1)'));
test('Zero area serialized rectangle is empty',()=>assert.equal(geometry(svg(region(5,[[5,5,5,35]]))).d,''));
for(const open of [false,true])test(`Extended region retains constructed/selected path: ${open}`,()=>{const r=[record(59),polygon()];if(!open)r.push(record(60));r.push(region());if(open)r.push(record(60));r.push(record(64,0,0,39,39));assert.equal(drawing(svg(...r)).d,'M 5 5 L 35 5 L 20 35 Z');});
test('Extended region does not move DC point',()=>{const a=drawing(svg(record(27,1,2),region(),record(54,8,9)));assert.equal(a.x1,'1');assert.equal(a.y1,'2');});
for(const mask of [false,true])test(`SaveRestore restores region across null reset: ${mask}`,()=>assert.equal(drawing(svg(region(),...(mask?[region(4)]:[]),record(33),record(75,0,5),record(34,-1),record(43,0,0,39,39)))[mask?'mask':'clip-path'],mask?'url(#mask2)':'url(#clip1)'));
for(const path of [false,true])test(`Extended region combines path or rectangle clip: ${path}`,()=>{const r=path?[record(59),polygon(),record(60),record(67,5),region(1),record(43,0,0,39,39)]:[record(30,5,5,35,35),region(1),record(43,0,0,39,39)];assert.equal(drawing(svg(...r)).mask,'url(#mask2)');});
for(const count of [0,1])test(`Truncated extended region fixed fields: ${count}`,()=>assert.equal(drawing(svg(region(),record(75,...Array(count).fill(0)),record(43,0,0,39,39)))['clip-path'],'url(#clip1)'));
for(const [at,value] of [[8,-1],[8,31],[8,49],[12,0],[12,6],[16,31],[16,36],[20,0],[20,2],[24,2],[24,-1],[28,15],[28,-1],[48,36]])test(`Malformed extended region retains previous clip: ${at}/${value}`,()=>{const s=svg(region(),change(region(),at,value),record(43,0,0,39,39));assert.equal([...s.matchAll(/<clipPath\b/g)].length,1);assert.equal(drawing(s)['clip-path'],'url(#clip1)');});
test('Definition IDs remain unique after null reset',()=>assert.equal(drawing(svg(region(),record(75,0,5),region(),record(43,0,0,39,39)))['clip-path'],'url(#clip2)'));
for(const reset of [false,true])test(`HTML compound region/reset preserves source: ${reset}`,async()=>{const r=[region(5,[[5,5,15,35],[25,5,35,35]])];if(reset)r.push(record(75,0,5));r.push(record(43,0,0,39,39));const b=emf(...r),original=Buffer.from(b),uri='data:image/emf;base64,'+b.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Region',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.equal(drawing(decodeURIComponent(match[1]))['clip-path'],reset?undefined:'url(#clip1)');assert.equal(item.source.staticValue,uri);assert.deepEqual(b,original);});
