import assert from 'node:assert/strict';
import test from 'node:test';
import {MetafileToSvgRenderer} from '../dist/images/converters/metafile-to-svg-renderer.js';
import {HmiGraphicView,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty as p} from '../dist/index.js';
function record(type,...values){const b=Buffer.alloc(8+values.length*4);b.writeUInt32LE(type);b.writeUInt32LE(b.length,4);values.forEach((v,i)=>b.writeUInt32LE(v>>>0,8+i*4));return b;}
function emf(...records){const b=Buffer.concat([Buffer.alloc(88),...records,record(14,0,0,20)]);for(const [at,v] of [[0,1],[4,88],[16,39],[20,39],[40,0x464d4520],[44,0x10000],[48,b.length],[52,records.length+2]])b.writeUInt32LE(v,at);b.writeUInt16LE(2,56);return b;}
function wrecord(type,...values){const b=Buffer.alloc(6+values.length*2);b.writeUInt32LE(b.length/2);b.writeUInt16LE(type,4);values.forEach((v,i)=>b.writeInt16LE(v,6+i*2));return b;}
function wmf(...records){const b=Buffer.concat([Buffer.alloc(18),...records,wrecord(0)]);b.writeUInt16LE(1);b.writeUInt16LE(9,2);b.writeUInt16LE(0x300,4);b.writeUInt32LE(b.length/2,6);b.writeUInt16LE(2,10);b.writeUInt32LE(Math.max(3,...records.map(r=>r.length/2)),12);return b;}
function polygon(){const b=Buffer.alloc(52);b.writeUInt32LE(3);b.writeUInt32LE(52,4);b.writeUInt32LE(3,24);[5,5,35,5,20,35].forEach((v,i)=>b.writeInt32LE(v,28+i*4));return b;}
const clip=(exclude,l=5,t=6,r=35,b=36)=>record(exclude?29:30,l,t,r,b),wclip=(exclude,l=5,t=6,r=35,b=36)=>wrecord(exclude?0x415:0x416,b,r,t,l);
const render=(b,wmf=false)=>new MetafileToSvgRenderer().render(b,wmf?'.wmf':'.emf'),svg=(...r)=>render(emf(...r));
const attrs=tag=>Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m=>[m[1],m[2]]));
const geometry=s=>attrs(s.match(/<path\b[^>]*>/)[0]),drawing=s=>attrs([...s.replace(/<defs>[^]*?<\/defs>/,'').matchAll(/<(?:path|rect|line)\b[^>]*>/g)].at(-1)[0]);
const bits=f=>{const b=Buffer.alloc(4);b.writeFloatLE(f);return b.readUInt32LE();};
for(const w of [false,true])for(const exclude of [false,true])test(`Rectangle clip native field order: ${w}/${exclude}`,()=>{const s=w?render(wmf(wrecord(0x20c,40,40),wclip(exclude),wrecord(0x213,20,39)),true):svg(clip(exclude),record(54,39,20));assert.equal(geometry(s).d,'M 5 6 L 35 6 L 35 36 L 5 36 Z');assert.equal(geometry(s)['clip-rule'],'nonzero');assert.equal(drawing(s)[exclude?'mask':'clip-path'],exclude?'url(#mask1)':'url(#clip1)');});
for(const w of [false,true])for(const exclude of [false,true])test(`Rectangle clip reversed bounds: ${w}/${exclude}`,()=>{const s=w?render(wmf(wclip(exclude,35,36,5,6),wrecord(0x41b,39,39,0,0)),true):svg(clip(exclude,35,36,5,6),record(43,0,0,39,39));assert.equal(geometry(s).d,'M 5 6 L 35 6 L 35 36 L 5 36 Z');});
for(const exclude of [false,true])for(const zeroHeight of [false,true])test(`Empty rectangle clip: ${exclude}/${zeroHeight}`,()=>{const s=svg(clip(exclude,5,6,zeroHeight?35:5,zeroHeight?6:36),record(54,39,20));assert.equal(geometry(s).d,'');assert.equal(drawing(s)[exclude?'mask':'clip-path'],exclude?'url(#mask1)':'url(#clip1)');});
for(const exclude of [false,true])test(`Rectangle clip preserves DC point: ${exclude}`,()=>{const a=drawing(svg(record(27,1,2),clip(exclude),record(54,8,9)));assert.equal(a.x1,'1');assert.equal(a.y1,'2');});
for(const exclude of [false,true])test(`Rectangle clip retains selected path: ${exclude}`,()=>assert.equal(drawing(svg(record(59),polygon(),record(60),clip(exclude),record(64,0,0,39,39))).d,'M 5 5 L 35 5 L 20 35 Z'));
for(const exclude of [false,true])test(`Rectangle clip does not modify open path: ${exclude}`,()=>assert.equal(drawing(svg(record(59),polygon(),clip(exclude),record(60),record(64,0,0,39,39))).d,'M 5 5 L 35 5 L 20 35 Z'));
for(const exclude of [false,true])test(`Rectangle clip rotates all corners: ${exclude}`,()=>assert.equal(geometry(svg(record(35,0,bits(1),bits(-1),0,bits(40),0),clip(exclude))).d,'M 34 5 L 34 35 L 4 35 L 4 5 Z'));
test('Sheared clip is not a bounding rectangle',()=>assert.equal(geometry(svg(record(35,bits(1),bits(.5),0,bits(1),0,0),clip(false))).d,'M 5 8.5 L 35 23.5 L 35 53.5 L 5 38.5 Z'));
for(const exclude of [false,true])test(`Rectangle clip viewport mapping: ${exclude}`,()=>assert.equal(geometry(svg(record(17,8),record(9,10,10),record(11,20,30),record(12,4,7),clip(exclude))).d,'M 14 25 L 74 25 L 74 115 L 14 115 Z'));
for(const exclude of [false,true])for(const mask of [false,true])test(`Rectangle combines existing clip or mask: ${exclude}/${mask}`,()=>{const r=[record(59),polygon(),record(60),record(67,5)];if(mask)r.push(record(59),polygon(),record(60),record(67,1));r.push(clip(exclude),record(43,0,0,39,39));const s=svg(...r),latest=[...s.matchAll(/<mask\b[^]*?<\/mask>/g)].at(-1)[0];assert.ok(latest.includes(mask?'mask="url(#mask2)"':'clip-path="url(#clip1)"'));assert.equal(drawing(s).mask,mask?'url(#mask3)':'url(#mask2)');});
for(const exclude of [false,true])test(`Rectangle clip SaveRestore returns unclipped: ${exclude}`,()=>{const a=drawing(svg(record(33),clip(exclude),record(34,-1),record(43,0,0,39,39)));assert.equal(a.mask,undefined);assert.equal(a['clip-path'],undefined);});
for(const exclude of [false,true])test(`Existing rectangle clip is frozen across mapping changes: ${exclude}`,()=>{const s=svg(clip(exclude),record(12,10,20),record(43,0,0,39,39));assert.equal(geometry(s).d,'M 5 6 L 35 6 L 35 36 L 5 36 Z');assert.equal(drawing(s).x,'10');});
for(const exclude of [false,true])for(const count of [0,1,2,3])test(`Truncated EMF rectangle clip: ${exclude}/${count}`,()=>{const s=svg(record(exclude?29:30,...Array(count).fill(5)),record(54,39,20));assert.equal([...s.matchAll(/<(?:clipPath|mask)\b/g)].length,0);assert.equal(drawing(s).mask,undefined);assert.equal(drawing(s)['clip-path'],undefined);});
for(const exclude of [false,true])for(const count of [0,1,2,3])test(`Truncated WMF rectangle clip: ${exclude}/${count}`,()=>{const s=render(wmf(wrecord(exclude?0x415:0x416,...Array(count).fill(5)),wrecord(0x213,20,39)),true);assert.equal([...s.matchAll(/<(?:clipPath|mask)\b/g)].length,0);});
test('WMF mask uses final inferred negative viewport',()=>{const s=render(wmf(wclip(true,-20,-20,-10,-10),wrecord(0x41b,30,30,-30,-30)),true),a=attrs(s.match(/<mask\b[^>]*>/)[0]);assert.equal(a.x,'-30');assert.equal(a.y,'-30');assert.equal(a.width,'60');assert.ok(!s.includes('__METAFILE_CLIP_VIEWPORT__'));});
test('WMF mask uses later explicit viewport',()=>{const s=render(wmf(wclip(true),wrecord(0x20b,-10,-20),wrecord(0x20c,50,60),wrecord(0x213,20,39)),true),a=attrs(s.match(/<mask\b[^>]*>/)[0]);assert.equal(a.x,'-20');assert.equal(a.y,'-10');assert.equal(a.width,'60');assert.equal(a.height,'50');});
for(const exclude of [false,true])test(`WMF mirrored rectangle clip: ${exclude}`,()=>{const s=render(wmf(wrecord(0x20c,-40,40),wclip(exclude),wrecord(0x213,20,39)),true);assert.match(s,/<g transform="translate\(/);assert.equal(drawing(s)[exclude?'mask':'clip-path'],exclude?'url(#mask1)':'url(#clip1)');});
for(const w of [false,true])for(const exclude of [false,true])test(`HTML rectangle clip preserves source: ${w}/${exclude}`,async()=>{const b=w?wmf(wrecord(0x20c,40,40),wclip(exclude),wrecord(0x41b,39,39,0,0)):emf(clip(exclude),record(43,0,0,39,39)),original=Buffer.from(b),uri='data:image/'+(w?'wmf':'emf')+';base64,'+b.toString('base64'),item=Object.assign(new HmiGraphicView(),{name:'Clip',source:p(uri)}),screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(item);const html=await new HmiScreenToHtmlConverter().convertAsync(screen),match=html.match(/src="data:image\/svg\+xml;charset=utf-8,([^"]+)"/);assert.ok(match);assert.ok(decodeURIComponent(match[1]).includes(exclude?'url(#mask1)':'url(#clip1)'));assert.equal(item.source.staticValue,uri);assert.deepEqual(b,original);});
