import assert from "node:assert/strict";import test from "node:test";
import {HmiNcKeyboardControl,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty,hmiColorFromArgb,getStaticValue} from "../dist/index.js";
for(const configured of [false,true]) test(`NC keyboard palette keeps distinct colors configured=${configured}`,async()=>{
 const c=new HmiNcKeyboardControl();c.name="Keyboard <A> & B";c.resizable=staticProperty(configured);assert.notEqual(c.normalKeys,c.specialKeys);assert.notEqual(c.specialKeys,c.enterKey);
 if(configured){c.keyboardStyle=staticProperty(-7);c.keyboardBackgroundColor=staticProperty(hmiColorFromArgb(0,1,2,3));for(const [appearance,red] of [[c.normalKeys,1],[c.specialKeys,21],[c.enterKey,41]]){appearance.normalBackgroundColor=staticProperty(hmiColorFromArgb(255,red,2,3));appearance.normalForegroundColor=staticProperty(hmiColorFromArgb(255,red+1,4,5));appearance.pressedBackgroundColor=staticProperty(hmiColorFromArgb(255,red+2,6,7));appearance.pressedForegroundColor=staticProperty(hmiColorFromArgb(255,red+3,8,9));}}
 const screen=new HmiScreen(),layer=new HmiLayer();screen.layers.push(layer);layer.items.push(c);const html=await new HmiScreenToHtmlConverter().convertAsync(screen);assert.ok(html.includes("NC keyboard layout not decoded"));assert.ok(html.includes('data-preview="palette"'));assert.ok(html.includes("Keyboard &lt;A&gt; &amp; B"));assert.equal(html.includes("data-keyboard-style="),configured);assert.equal(html.includes("overflow: hidden;resize: both;"),configured);
 if(configured){assert.ok(html.includes('data-keyboard-style="-7"'));assert.equal(getStaticValue(c.keyboardBackgroundColor)?.alpha,0);}
 const hex=r=>r.toString(16).padStart(2,"0").toUpperCase();
 for(const [kind,red] of [["normal",1],["special",21],["enter",41]]){const row=html.match(new RegExp(`<tr data-key-class="${kind}">(.*?)</tr>`,"u"))?.[1] ?? "";assert.ok(row.length>0);const spans=[...row.matchAll(/<span[^>]*>(.*?)<\/span>/gu)];assert.equal(spans.length,2);for(const span of spans)assert.equal(span[0].includes("data-background-color="),configured);
 if(configured){assert.ok(spans[0][0].includes(`background-color: #${hex(red)}0203;`));assert.ok(spans[0][0].includes(`color: #${hex(red+1)}0405;`));assert.ok(spans[1][0].includes(`background-color: #${hex(red+2)}0607;`));assert.ok(spans[1][0].includes(`color: #${hex(red+3)}0809;`));}else for(const span of spans)assert.ok(span[0].includes("Not configured"));}
});
