import assert from "node:assert/strict";
import test from "node:test";
import {withoutRuntimeScripts} from "./html-test-markup.js";
import {HmiDetailedParameterControl,HmiOverviewParameterControl,HmiParameterColumn,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty,hmiColorFromArgb,getStaticValue} from "../dist/index.js";
for(const Type of [HmiDetailedParameterControl,HmiOverviewParameterControl]) test(`Parameter grid and scroll modes keep headers/permissions independent: ${Type.name}`,async()=>{
  const control=new Type();control.width=staticProperty(600);control.height=staticProperty(200);control.gridLineWidth=staticProperty(2.5);control.gridLineColor=staticProperty(hmiColorFromArgb(255,17,34,51));control.headerBorderColor=staticProperty(hmiColorFromArgb(255,68,85,102));control.columnDefinitions.push(Object.assign(new HmiParameterColumn(),{name:"Column <A>",allowSort:staticProperty(true)}),Object.assign(new HmiParameterColumn(),{name:"Column <B>",allowSort:staticProperty(false)}));
  const screen=new HmiScreen(),layer=new HmiLayer();layer.items.push(control);screen.layers.push(layer);const renderer=new HmiScreenToHtmlConverter(),htmlFor=async()=>withoutRuntimeScripts(await renderer.convertAsync(screen)),details=html=>html.match(/<div class="hmi-parameter-details"[^>]*>/u)?.[0]??"";
  let html=await htmlFor();assert.ok(details(html).includes("border-top-width: 2.5px;"));assert.ok(!html.includes("data-grid-line-visibility="));assert.ok(!html.includes("data-allow-sort-by-column="));control.allowSortByColumn=staticProperty(false);control.allowFilterByColumn=staticProperty(true);
  for(const mode of [0,1,2,3,37,-2147483648,2147483647]) { control.gridLineVisibility=staticProperty(mode);control.gridSelectionMode=staticProperty(mode);control.coloringMode=staticProperty(mode);html=await htmlFor();assert.ok(details(html).includes(`border-top-width: ${mode===2?"2.5":"0"}px;`));
    for(const key of ["grid-line-visibility","grid-selection-mode","coloring-mode"]) assert.ok(html.includes(`data-${key}="${mode}"`),key);
    for(const part of ["border-right-color: #445566;","border-right-width: 2.5px;",'data-allow-sort-by-column="false"','data-allow-filter-by-column="true"','data-allow-sort="true"',"Column &lt;A&gt;","Parameter data not loaded"]) assert.ok(html.includes(part),part);assert.equal([...html.matchAll(/<tr>/gu)].length,2);assert.ok(!html.includes("<button"));
  }
  for(const [x,y] of [[0,1],[1,2],[2,0]]) { control.horizontalScrollBarVisibility=staticProperty(x);control.verticalScrollBarVisibility=staticProperty(y);html=await htmlFor();const overflow=mode=>mode===0?"auto":mode===1?"scroll":"hidden";assert.ok(details(html).includes(`overflow-x: ${overflow(x)};`));assert.ok(details(html).includes(`overflow-y: ${overflow(y)};`)); }
  control.horizontalScrollBarVisibility=staticProperty(37);control.verticalScrollBarVisibility=staticProperty(-2147483648);html=await htmlFor();assert.ok(!details(html).includes("overflow-x:"));assert.ok(!details(html).includes("overflow-y:"));assert.ok(html.includes('data-horizontal-scroll-bar-visibility="37"'));assert.ok(html.includes('data-vertical-scroll-bar-visibility="-2147483648"'));
  if(control instanceof HmiDetailedParameterControl) { control.hideDetails=staticProperty(true);html=await htmlFor();assert.ok(!html.includes('class="hmi-parameter-details"'));assert.ok(html.includes('data-grid-selection-mode="2147483647"'));assert.ok(html.includes('data-allow-sort-by-column="false"')); }
  assert.equal(control.columnDefinitions.length,2);assert.equal(getStaticValue(control.columnDefinitions[0].allowSort),true);assert.equal(getStaticValue(control.horizontalScrollBarVisibility),37);
});
