import assert from "node:assert/strict";
import test from "node:test";
import { HmiDetailedParameterControl,HmiOverviewParameterControl,HmiParameterColumn,HmiScreen,HmiLayer,HmiFont,HmiScreenToHtmlConverter,HmiHtmlConvertOptions,staticProperty,hmiColorFromArgb,getStaticValue } from "../dist/index.js";
for(const Type of [HmiDetailedParameterControl,HmiOverviewParameterControl]) test(`Parameter selection sample is optional and separate: ${Type.name}`,async()=>{
  const control=new Type();control.name="Control <A>";const screen=new HmiScreen(),layer=new HmiLayer();layer.items.push(control);screen.layers.push(layer);const renderer=new HmiScreenToHtmlConverter();assert.ok(!(await renderer.convertAsync(screen)).includes("hmi-parameter-selection-preview"));
  control.selectFullRow=staticProperty(false);let html=await renderer.convertAsync(screen);assert.ok(html.includes("Selection appearance preview · Cell"));assert.ok(html.includes('data-select-full-row="false"'));
  control.selectFullRow=staticProperty(true);control.selectionBackgroundColor=staticProperty(hmiColorFromArgb(0,17,34,51));control.selectionForegroundColor=staticProperty(hmiColorFromArgb(255,68,85,102));control.selectionBorderColor=staticProperty(hmiColorFromArgb(255,119,136,153));control.selectionBorderWidth=staticProperty(0);control.contentBackgroundColor=staticProperty(hmiColorFromArgb(255,1,2,3));
  const font=(name,size)=>{const f=new HmiFont();f.name=staticProperty(name);f.size=staticProperty(size);return f;};control.contentFont=font("Content",13);control.contentFont.localizedFonts.set(1031,font("Localized <A> & B",17));control.columnDefinitions.push(Object.assign(new HmiParameterColumn(),{name:"Column <A>"}));
  const options=new HmiHtmlConvertOptions();options.cultureLcid=1031;html=await renderer.convertAsync(screen,undefined,options);let sample=html.match(/<div class="hmi-parameter-selection-preview"[^>]*>/u)?.[0]??"";
  for(const part of ["background-color: rgba(17,34,51,0);","color: #445566;","border-color: #778899;","border-width: 0px;","font-family: Localized &lt;A&gt; &amp; B;font-size: 17px;"]) assert.ok(sample.includes(part),part);
  assert.ok(!sample.includes("#010203"));assert.ok(html.includes("Selection appearance preview · Entire row"));assert.ok(html.includes("Parameter data not loaded"));assert.ok(html.includes("Column &lt;A&gt;"));options.cultureLcid=1036;
  sample=(await renderer.convertAsync(screen,undefined,options)).match(/<div class="hmi-parameter-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("font-family: Content;font-size: 13px;"));
  for(const width of [-2,NaN,Infinity]) { control.selectionBorderWidth=staticProperty(width);sample=(await renderer.convertAsync(screen)).match(/<div class="hmi-parameter-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(!sample.includes("border-width:"));assert.ok(!sample.includes("border-style:")); }
  control.selectionBorderWidth=staticProperty(2.5);sample=(await renderer.convertAsync(screen)).match(/<div class="hmi-parameter-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("border-width: 2.5px;"));
  if(control instanceof HmiDetailedParameterControl) { control.hideDetails=staticProperty(true);html=await renderer.convertAsync(screen);assert.ok(!html.includes("hmi-parameter-selection-preview"));assert.ok(html.includes('data-selection-border-width="2.5"'));assert.equal(control.columnDefinitions.length,1); }
  assert.equal(getStaticValue(control.selectionBorderWidth),2.5);assert.deepEqual(getStaticValue(control.selectionBackgroundColor),hmiColorFromArgb(0,17,34,51));
});
