import assert from "node:assert/strict";
import test from "node:test";
import { HmiDetailedParameterControl,HmiOverviewParameterControl,HmiParameterColumn,HmiScreen,HmiLayer,HmiFont,HmiScreenToHtmlConverter,HmiHtmlConvertOptions,staticProperty,hmiColorFromArgb } from "../dist/index.js";
import { withoutRuntimeScripts } from "./html-test-markup.js";
for(const Type of [HmiDetailedParameterControl,HmiOverviewParameterControl]) test(`Parameter header selection/configuration remain independent: ${Type.name}`,async()=>{
  const control=new Type();control.name="Header <A>";const screen=new HmiScreen(),layer=new HmiLayer();layer.items.push(control);screen.layers.push(layer);const renderer=new HmiScreenToHtmlConverter();const htmlFor=async()=>withoutRuntimeScripts(await renderer.convertAsync(screen));
  assert.ok(!(await htmlFor()).includes("hmi-parameter-header-selection-preview"));assert.ok(!(await htmlFor()).includes("data-column-header-type"));
  control.allowColumnReorder=staticProperty(false);control.allowColumnResize=staticProperty(true);control.columnHeaderType=staticProperty(0);control.rowHeaderType=staticProperty(-2147483648);control.headerSelectionForegroundColor=staticProperty(hmiColorFromArgb(255,68,85,102));
  let html=await htmlFor(),sample=html.match(/<div class="hmi-parameter-header-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("color: #445566;"));assert.ok(!sample.includes("background-color:"));for(const part of ['data-allow-column-reorder="false"','data-allow-column-resize="true"','data-column-header-type="0"','data-row-header-type="-2147483648"'])assert.ok(html.includes(part),part);
  control.headerSelectionBackgroundColor=staticProperty(hmiColorFromArgb(0,17,34,51));control.headerBackgroundColor=staticProperty(hmiColorFromArgb(255,1,2,3));control.selectionBackgroundColor=staticProperty(hmiColorFromArgb(255,119,136,153));
  const font=(name,size)=>{const f=new HmiFont();f.name=staticProperty(name);f.size=staticProperty(size);return f;};control.headerFont=font("Header",13);control.headerFont.localizedFonts.set(1031,font("Localized <A> & B",17));control.columnDefinitions.push(Object.assign(new HmiParameterColumn(),{name:"Column <A>"}));
  const options=new HmiHtmlConvertOptions();options.cultureLcid=1031;html=withoutRuntimeScripts(await renderer.convertAsync(screen,undefined,options));sample=html.match(/<div class="hmi-parameter-header-selection-preview"[^>]*>/u)?.[0]??"";
  for(const part of ["background-color: rgba(17,34,51,0);","color: #445566;","font-family: Localized &lt;A&gt; &amp; B;font-size: 17px;"])assert.ok(sample.includes(part),part);assert.ok(!sample.includes("#010203"));assert.ok(!sample.includes("#778899"));assert.ok(html.includes("Column &lt;A&gt;"));assert.ok(html.includes("Parameter data not loaded"));assert.ok(html.includes("Header selection appearance preview"));assert.equal([...html.matchAll(/<tr[ >]/gu)].length,2);assert.ok(!html.includes("<button"));
  options.cultureLcid=1036;sample=withoutRuntimeScripts(await renderer.convertAsync(screen,undefined,options)).match(/<div class="hmi-parameter-header-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("font-family: Header;font-size: 13px;"));
  control.headerSelectionForegroundColor=undefined;sample=(await htmlFor()).match(/<div class="hmi-parameter-header-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(!sample.includes("color: #"));assert.ok(sample.includes("background-color: rgba(17,34,51,0);"));
  if(control instanceof HmiDetailedParameterControl) {control.hideDetails=staticProperty(true);html=await htmlFor();assert.ok(!html.includes('class="hmi-parameter-header-selection-preview"'));assert.ok(html.includes('data-row-header-type="-2147483648"'));assert.ok(html.includes("data-header-selection-background-color"));assert.equal(control.columnDefinitions.length,1);}
});
