import assert from "node:assert/strict";
import test from "node:test";
import { HmiDetailedParameterControl,HmiOverviewParameterControl,HmiScreen,HmiLayer,HmiScreenToHtmlConverter,staticProperty,getStaticValue } from "../dist/index.js";
import { withoutRuntimeScripts } from "./html-test-markup.js";
for(const Type of [HmiDetailedParameterControl,HmiOverviewParameterControl]) test(`Parameter bar layout/enablement remain independent: ${Type.name}`,async()=>{
  const control=new Type(),screen=new HmiScreen(),layer=new HmiLayer();layer.items.push(control);screen.layers.push(layer);const renderer=new HmiScreenToHtmlConverter();control.showToolbar=staticProperty(true);control.showStatusBar=staticProperty(true);const htmlFor=async()=>withoutRuntimeScripts(await renderer.convertAsync(screen));const bar=(html,name)=>html.match(new RegExp('<div class="hmi-parameter-'+name+'"[^>]*>','u'))?.[0]??"";
  let html=await htmlFor();assert.ok(!html.includes("data-toolbar-enabled"));assert.ok(!bar(html,"toolbar").includes("aria-disabled"));assert.ok(bar(html,"toolbar").includes("padding: 2px 4px;"));
  control.toolbarEnabled=staticProperty(false);control.toolbarShowToolTips=staticProperty(true);control.toolbarPaddingLeft=staticProperty(0);control.toolbarPaddingTop=staticProperty(2.5);control.toolbarPaddingRight=staticProperty(-3);control.toolbarPaddingBottom=staticProperty(4);control.statusBarEnabled=staticProperty(true);control.statusBarShowToolTips=staticProperty(false);control.statusBarPaddingLeft=staticProperty(7.5);
  html=await htmlFor();const toolbar=bar(html,"toolbar");for(const part of ["padding-left: 0px;","padding-top: 2.5px;","padding-bottom: 4px;",'aria-disabled="true"'])assert.ok(toolbar.includes(part),part);assert.ok(!toolbar.includes("padding-right:"));const status=bar(html,"status-bar");assert.ok(status.includes("padding-left: 7.5px;"));assert.ok(status.includes('aria-disabled="false"'));assert.ok(!status.includes("padding-top:"));assert.ok(html.includes('data-toolbar-padding-right="-3"'));assert.ok(html.includes('data-status-bar-show-tooltips="false"'));assert.ok(!html.includes("<button"));assert.ok(!html.includes("title="));
  for(const width of [-2,NaN,Infinity]) {control.statusBarPaddingRight=staticProperty(width);assert.ok(!bar(await htmlFor(),"status-bar").includes("padding-right:"));}control.statusBarPaddingRight=staticProperty(0);assert.ok(bar(await htmlFor(),"status-bar").includes("padding-right: 0px;"));
  control.showToolbar=staticProperty(false);control.showStatusBar=staticProperty(false);html=await htmlFor();assert.equal(bar(html,"toolbar"),"");assert.equal(bar(html,"status-bar"),"");assert.ok(html.includes('data-toolbar-enabled="false"'));assert.ok(html.includes('data-status-bar-padding-left="7.5"'));assert.equal(getStaticValue(control.toolbarPaddingRight),-3);assert.equal(getStaticValue(control.statusBarEnabled),true);
});
