import assert from "node:assert/strict";
import test from "node:test";
import {HmiRecipeControl,HmiRecipeViewKind,HmiRecipeColumn,HmiMultilingualText,HmiScreen,HmiLayer,HmiFont,HmiScreenToHtmlConverter,HmiHtmlConvertOptions,staticProperty,hmiColorFromArgb} from "../dist/index.js";
import {withoutRuntimeScripts} from "./html-test-markup.js";
for(const selector of [false,true])test(`Recipe selection is independent and headers use plain localized text selector=${selector}`,async()=>{
 const control=new HmiRecipeControl();control.viewKind=selector?HmiRecipeViewKind.Selector:HmiRecipeViewKind.Table;control.defaultRecipeName=staticProperty("Recipe <A>");const screen=new HmiScreen(),layer=new HmiLayer();layer.items.push(control);screen.layers.push(layer);const renderer=new HmiScreenToHtmlConverter(),options=new HmiHtmlConvertOptions();options.cultureLcid=1031;const htmlFor=async()=>withoutRuntimeScripts(await renderer.convertAsync(screen,undefined,options));
 assert.ok(!(await htmlFor()).includes("hmi-recipe-selection-preview"));assert.ok(!(await htmlFor()).includes("data-selection-background-color"));control.selectionForegroundColor=staticProperty(hmiColorFromArgb(255,68,85,102));let html=await htmlFor(),sample=html.match(/<div class="hmi-recipe-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("color: #445566;"));assert.ok(!sample.includes("background-color:"));
 control.selectionBackgroundColor=staticProperty(hmiColorFromArgb(0,17,34,51));control.contentBackgroundColor=staticProperty(hmiColorFromArgb(255,1,2,3));control.headerBackgroundColor=staticProperty(hmiColorFromArgb(255,119,136,153));const font=(name,size)=>{const f=new HmiFont();f.name=staticProperty(name);f.size=staticProperty(size);return f;};control.contentFont=font("Content",13);control.contentFont.localizedFonts.set(1031,font("Localized <A> & B",17));
 const header=HmiMultilingualText.fromText("Plain <A> & B",1031);header.texts.set(1033,"English");header.formattedTexts.set(1031,"<b>Formatted payload</b>");control.columnDefinitions.push(Object.assign(new HmiRecipeColumn(),{headerText:header}));const empty=HmiMultilingualText.fromText("",1031);empty.formattedTexts.set(1031,"<b>Must stay empty</b>");control.columnDefinitions.push(Object.assign(new HmiRecipeColumn(),{headerText:empty}));
 html=await htmlFor();sample=html.match(/<div class="hmi-recipe-selection-preview"[^>]*>/u)?.[0]??"";for(const part of ["background-color: rgba(17,34,51,0);","color: #445566;","font-family: Localized &lt;A&gt; &amp; B;font-size: 17px;"])assert.ok(sample.includes(part),part);assert.ok(!sample.includes("#010203"));assert.ok(!sample.includes("#778899"));assert.ok(html.includes("data-selection-background-color"));assert.ok(html.includes("Selection appearance preview"));assert.ok(!html.includes("Formatted payload"));assert.ok(!html.includes("Must stay empty"));assert.ok(!html.includes("<button"));
 if(!selector){assert.ok(html.includes("Plain &lt;A&gt; &amp; B</th>"));assert.ok(html.includes(">Recipe data not loaded</td>"));assert.ok(html.includes("></th>"));assert.equal([...html.matchAll(/<tr[ >]/gu)].length,2);}else assert.ok(html.includes("Recipe &lt;A&gt;"));
 options.cultureLcid=1033;html=await htmlFor();sample=html.match(/<div class="hmi-recipe-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(sample.includes("font-family: Content;font-size: 13px;"));if(!selector)assert.ok(html.includes("English</th>"));
 control.showHeader=staticProperty(false);html=await htmlFor();assert.ok(!html.includes("<th "));assert.ok(html.includes("Selection appearance preview"));control.selectionForegroundColor=undefined;sample=(await htmlFor()).match(/<div class="hmi-recipe-selection-preview"[^>]*>/u)?.[0]??"";assert.ok(!sample.includes("color: #"));assert.ok(sample.includes("background-color: rgba(17,34,51,0);"));assert.equal(header.formattedTexts.get(1031),"<b>Formatted payload</b>");
});
