import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const htmlRoot = resolve(root, "html");
const bundlePath = resolve(htmlRoot, "dist", "base-hmi-runtime.js");
const csharpPath = resolve(root, "src", "BaseHmiTypes", "Converters", "Html", "HmiHtmlRuntimeModule.Generated.cs");
const typescriptPath = resolve(
  root,
  "typescript",
  "base-hmi-types",
  "src",
  "converters",
  "html",
  "HmiHtmlRuntimeModule.generated.ts",
);

await build({
  bundle: true,
  entryPoints: [resolve(htmlRoot, "src", "index.ts")],
  format: "esm",
  minify: true,
  outfile: bundlePath,
  platform: "browser",
  sourcemap: false,
  target: "es2022",
});

const runtime = (await readFile(bundlePath, "utf8")).replaceAll("</script", "<\\/script");

await writeGeneratedCsharp(runtime);
await writeGeneratedTypescript(runtime);

async function writeGeneratedCsharp(script) {
  const chunks = chunkString(script, 8000).map((chunk) => "        " + toCsharpStringLiteral(chunk));
  const source = `// <auto-generated />
namespace BaseHmiTypes.Converters.Html;

internal static class HmiHtmlRuntimeModule
{
    internal static readonly string Script = string.Concat(
${chunks.join(",\n")});
}
`;
  await mkdir(dirname(csharpPath), { recursive: true });
  await writeFile(csharpPath, source, "utf8");
}

async function writeGeneratedTypescript(script) {
  const source = `// <auto-generated />
export const hmiHtmlRuntimeModuleScript = ${JSON.stringify(script)};
`;
  await mkdir(dirname(typescriptPath), { recursive: true });
  await writeFile(typescriptPath, source, "utf8");
}

function chunkString(value, size) {
  const chunks = [];
  for (let index = 0; index < value.length; index += size) {
    chunks.push(value.slice(index, index + size));
  }
  return chunks.length === 0 ? [""] : chunks;
}

function toCsharpStringLiteral(value) {
  let result = "\"";
  for (const character of value) {
    switch (character) {
      case "\\":
        result += "\\\\";
        break;
      case "\"":
        result += "\\\"";
        break;
      case "\r":
        result += "\\r";
        break;
      case "\n":
        result += "\\n";
        break;
      case "\t":
        result += "\\t";
        break;
      default:
        result += character;
        break;
    }
  }
  return result + "\"";
}
