export enum HmiFillPattern {
  Transparent = "Transparent",
  Solid = "Solid",
  DiagonalLeftToRight = "DiagonalLeftToRight",
  Checkers = "Checkers",
  DiagonalCross = "DiagonalCross",
  DiagonalRightToLeft = "DiagonalRightToLeft",
  Horizontal = "Horizontal",
  Vertical = "Vertical",
  DottedHorizontal = "DottedHorizontal",
  DottedEvenOdd = "DottedEvenOdd",
  DottedEvenOddFiner = "DottedEvenOddFiner",
  DiagonalCrossFiner = "DiagonalCrossFiner",
  DottedEvenOddFinest = "DottedEvenOddFinest",
  HorizontalDifferentLines = "HorizontalDifferentLines",
  CheckersFiner = "CheckersFiner",
  DiagonalCrossBold = "DiagonalCrossBold",
  DottedHorizontalInverted = "DottedHorizontalInverted",
  Bricks = "Bricks",
  BricksDiagonal = "BricksDiagonal",
  Diagonal = "Diagonal",
}
