import { HmiControlWindowBase } from "./HmiControlWindowBase.js";
import { HmiColor } from "./HmiColor.js";
import { HmiLineStyle } from "./HmiLineStyle.js";
import { HmiProperty } from "./HmiProperty.js";
import { HmiTrendChartStyle } from "./HmiTrendChartStyle.js";
import { HmiTrendAxisScalingMode } from "./HmiTrendAxisScalingMode.js";
import { HmiTrendDataPointConnection } from "./HmiTrendDataPointConnection.js";
import { HmiTrendNumericRadix } from "./HmiTrendNumericRadix.js";
import { HmiTrendLegendPosition } from "./HmiTrendLegendPosition.js";
import { HmiTrendOverlay } from "./HmiTrendOverlay.js";
import { HmiTrendPen } from "./HmiTrendPen.js";
import { HmiTrendPenCaptionMode } from "./HmiTrendPenCaptionMode.js";
import { HmiTrendScrollMode } from "./HmiTrendScrollMode.js";
import { HmiTrendStackAxesMode } from "./HmiTrendStackAxesMode.js";
import { HmiTrendTimeFormat } from "./HmiTrendTimeFormat.js";
import { HmiTrendTemplateOption } from "./HmiTrendTemplateOption.js";
import { HmiTrendUpdateMode } from "./HmiTrendUpdateMode.js";
import { HmiTrendYAxisRangeMode } from "./HmiTrendYAxisRangeMode.js";
import { HmiTrendYAxisScaleMode } from "./HmiTrendYAxisScaleMode.js";

export abstract class HmiTrendControlBase extends HmiControlWindowBase {
  readonly pens: HmiTrendPen[] = [];
  readonly overlays: HmiTrendOverlay[] = [];
  readonly templateOptions: HmiTrendTemplateOption[] = [];
  minimumValue?: HmiProperty<number>;
  maximumValue?: HmiProperty<number>;
  chartStyle?: HmiProperty<HmiTrendChartStyle>;
  xAxisPenNumber?: HmiProperty<number>;
  updateMode?: HmiProperty<HmiTrendUpdateMode>;
  refreshRateMilliseconds?: HmiProperty<number>;
  heartbeatMilliseconds?: HmiProperty<number>;
  deadbandPercent?: HmiProperty<number>;
  timeFormat?: HmiProperty<HmiTrendTimeFormat>;
  numericRadix?: HmiProperty<HmiTrendNumericRadix>;
  dataPointConnection?: HmiProperty<HmiTrendDataPointConnection>;
  displayMilliseconds?: HmiProperty<boolean>;
  displayPenIcons?: HmiProperty<boolean>;
  allowScrolling?: HmiProperty<boolean>;
  scrollMode?: HmiProperty<HmiTrendScrollMode>;
  bufferSizePerPen?: HmiProperty<number>;
  chartTitle?: string;
  displayChartTitle?: HmiProperty<boolean>;
  dataServerName?: string;
  displayHistoricalLoadProgress?: HmiProperty<boolean>;
  displayLineLegend?: HmiProperty<boolean>;
  displayLineLegendMinimumMaximum?: HmiProperty<boolean>;
  lineLegendPenCaptionMode?: HmiProperty<HmiTrendPenCaptionMode>;
  lineLegendMaximumCaptionLength?: HmiProperty<number>;
  lineLegendPosition?: HmiProperty<HmiTrendLegendPosition>;
  lineLegendMaximumVisiblePens?: HmiProperty<number>;
  displayCurrentValueLegend?: HmiProperty<boolean>;
  currentValueLegendDisplayPenIcons?: HmiProperty<boolean>;
  currentValueLegendDisplayValues?: HmiProperty<boolean>;
  currentValueLegendDisplayTime?: HmiProperty<boolean>;
  xAxisScaleVisible?: HmiProperty<boolean>;
  xAxisDateVisible?: HmiProperty<boolean>;
  xAxisGridVisible?: HmiProperty<boolean>;
  xAxisMajorGridLineCount?: HmiProperty<number>;
  xAxisMinorGridLineCount?: HmiProperty<number>;
  xAxisGridColor?: HmiProperty<HmiColor>;
  /** Engineering-system date text used at the left edge when scrolling is disabled. */
  xAxisStartDate?: string;
  /** Engineering-system time text used at the left edge when scrolling is disabled. */
  xAxisStartTime?: string;
  xAxisTimeSpan?: HmiProperty<number>;
  xAxisTimeSpanUnit?: string;
  yAxisRangeMode?: HmiProperty<HmiTrendYAxisRangeMode>;
  yAxisIsolatedGraphing?: HmiProperty<boolean>;
  yAxisIsolationPercent?: HmiProperty<number>;
  yAxisScaleVisible?: HmiProperty<boolean>;
  yAxisDecimalPlaces?: HmiProperty<number>;
  yAxisGridVisible?: HmiProperty<boolean>;
  yAxisMajorGridLineCount?: HmiProperty<number>;
  yAxisMinorGridLineCount?: HmiProperty<number>;
  yAxisGridColor?: HmiProperty<HmiColor>;
  yAxisScaleMode?: HmiProperty<HmiTrendYAxisScaleMode>;
  yAxisScalePenNumber?: HmiProperty<number>;
  readonly runtimePropertyTabs: string[] = [];
  allowEditingLegendProperties?: HmiProperty<boolean>;
  allowPanZoom?: HmiProperty<boolean>;
  allowPauseResumeScrolling?: HmiProperty<boolean>;
  allowShowHideValueBar?: HmiProperty<boolean>;
  allowSnapshotCreation?: HmiProperty<boolean>;
  allowOverlayOptions?: HmiProperty<boolean>;
  allowPrint?: HmiProperty<boolean>;
  allowDeltaValueBar?: HmiProperty<boolean>;
  allowExportTrendData?: HmiProperty<boolean>;
  allowExportDataLogModelData?: HmiProperty<boolean>;
  showToolbar?: HmiProperty<boolean>;
  showTimePeriodBar?: HmiProperty<boolean>;
  showTagExplorer?: HmiProperty<boolean>;
  collapseTagExplorer?: HmiProperty<boolean>;
  showTagList?: HmiProperty<boolean>;
  collapseTagList?: HmiProperty<boolean>;
  showXAxisCursors?: HmiProperty<boolean>;
  showYAxisCursors?: HmiProperty<boolean>;
  singleTraceMode?: HmiProperty<boolean>;
  rubberBandZoomEnabled?: HmiProperty<boolean>;
  timePeriodAbsoluteMode?: HmiProperty<boolean>;
  timePeriodDuration?: HmiProperty<string>;
  timePeriodStart?: HmiProperty<string>;
  timePeriodEnd?: HmiProperty<string>;
  showAlarmCursor?: HmiProperty<boolean>;
  showEventList?: HmiProperty<boolean>;
  collapseEventList?: HmiProperty<boolean>;
  legacyShowAlarmEventList?: HmiProperty<boolean>;
  legacyCollapseAlarmEventList?: HmiProperty<boolean>;
  activeTraceIndex?: HmiProperty<number>;
  activeTraceVisible?: HmiProperty<boolean>;
  activeTraceJoinPoints?: HmiProperty<boolean>;
  activeTraceLineColor?: HmiProperty<HmiColor>;
  activeTraceLineStyle?: HmiProperty<HmiLineStyle>;
  activeTraceLineWidth?: HmiProperty<number>;
  activeTraceDecimalFormat?: HmiProperty<boolean>;
  activeTraceNumericPrecision?: HmiProperty<number>;
  activePlottingAlgorithmLinear?: HmiProperty<boolean>;
  activeMarkerColor?: HmiProperty<HmiColor>;
  activeMarkerShape?: HmiProperty<number>;
  activeMarkerSize?: HmiProperty<number>;
  activeMarkerVisible?: HmiProperty<boolean>;
  activeXAxisColor?: HmiProperty<HmiColor>;
  activeXAxisGridLinesVisible?: HmiProperty<boolean>;
  activeXAxisLineWidth?: HmiProperty<number>;
  activeXAxisMajorTickScale?: HmiProperty<number>;
  activeXAxisMaximumValue?: HmiProperty<number>;
  activeXAxisMinorTickMarks?: HmiProperty<number>;
  activeXAxisMinimumValue?: HmiProperty<number>;
  activeXAxisScalingMode?: HmiProperty<HmiTrendAxisScalingMode>;
  activeXAxisVisible?: HmiProperty<boolean>;
  activeYAxisColor?: HmiProperty<HmiColor>;
  activeYAxisGridLinesVisible?: HmiProperty<boolean>;
  activeYAxisLineWidth?: HmiProperty<number>;
  activeYAxisMajorTickScale?: HmiProperty<number>;
  activeYAxisMaximumValue?: HmiProperty<number>;
  activeYAxisMinorTickMarks?: HmiProperty<number>;
  activeYAxisMinimumValue?: HmiProperty<number>;
  activeYAxisScalingMode?: HmiProperty<HmiTrendAxisScalingMode>;
  activeYAxisVisible?: HmiProperty<boolean>;
  controlType?: string;
  currentTagName?: string;
  currentXTagName?: string;
  currentYTagName?: string;
  useCustomFileExplorer?: HmiProperty<boolean>;
  autoScale?: HmiProperty<boolean>;
  chartLiveMode?: HmiProperty<boolean>;
  chartZoomPercent?: HmiProperty<number>;
  stackAxesMode?: HmiProperty<HmiTrendStackAxesMode>;
  windowBackgroundColor?: HmiProperty<HmiColor>;
}
