import { HmiControlWindowBase } from "./HmiControlWindowBase.js";
import { HmiMultilingualText } from "../../common/HmiMultilingualText.js";
import { HmiColor } from "./HmiColor.js";
import { HmiFont } from "./HmiFont.js";
import { HmiHorizontalAlignment } from "./HmiHorizontalAlignment.js";
import { HmiVerticalAlignment } from "./HmiVerticalAlignment.js";
import { HmiLineStyle } from "./HmiLineStyle.js";
import { HmiProperty } from "./HmiProperty.js";
import { HmiThickness } from "./HmiThickness.js";
import { HmiTrendChartStyle } from "./HmiTrendChartStyle.js";
import { HmiTrendContainerType } from "./HmiTrendContainerType.js";
import { HmiTrendAxisScalingMode } from "./HmiTrendAxisScalingMode.js";
import { HmiTrendBatch } from "./HmiTrendBatch.js";
import { HmiTrendDataPointConnection } from "./HmiTrendDataPointConnection.js";
import { HmiTrendDataServer } from "./HmiTrendDataServer.js";
import { HmiTrendNumericRadix } from "./HmiTrendNumericRadix.js";
import { HmiTrendLegendPosition } from "./HmiTrendLegendPosition.js";
import { HmiTrendOverlay } from "./HmiTrendOverlay.js";
import { HmiTrendStatusBarPanel } from "../controls/HmiTrendStatusBarPanel.js";
import { HmiTrendPen } from "./HmiTrendPen.js";
import { HmiTrendValueAxis } from "./HmiTrendValueAxis.js";
import { HmiTrendXValueAxis } from "./HmiTrendXValueAxis.js";
import { HmiTrendWindow } from "./HmiTrendWindow.js";
import { HmiTrendTimeAxis } from "./HmiTrendTimeAxis.js";
import { HmiTrendPenCaptionMode } from "./HmiTrendPenCaptionMode.js";
import { HmiTrendScrollMechanism } from "./HmiTrendScrollMechanism.js";
import { HmiTrendScrollMode } from "./HmiTrendScrollMode.js";
import { HmiTrendStackAxesMode } from "./HmiTrendStackAxesMode.js";
import { HmiTrendTimeFormat } from "./HmiTrendTimeFormat.js";
import { HmiTrendTimeBase } from "./HmiTrendTimeBase.js";
import { HmiTrendTemplateOption } from "./HmiTrendTemplateOption.js";
import { HmiTrendUpdateMode } from "./HmiTrendUpdateMode.js";
import { HmiTrendYAxisRangeMode } from "./HmiTrendYAxisRangeMode.js";
import { HmiTrendYAxisCustomBoundSource } from "./HmiTrendYAxisCustomBoundSource.js";
import { HmiTrendYAxisScaleMode } from "./HmiTrendYAxisScaleMode.js";
import { HmiTrendWindowStyle } from "./HmiTrendWindowStyle.js";

export abstract class HmiTrendControlBase extends HmiControlWindowBase {
  definitionVersion?: number;
  readonly pens: HmiTrendPen[] = [];
  /** Configured value axes, including axes with no assigned pen. */
  readonly valueAxes: HmiTrendValueAxis[] = [];
  /** Configured numeric X axes for XY plots, including unassigned axes. */
  readonly xValueAxes: HmiTrendXValueAxis[] = [];
  readonly trendWindows: HmiTrendWindow[] = [];
  readonly timeAxes: HmiTrendTimeAxis[] = [];
  readonly overlays: HmiTrendOverlay[] = [];
  readonly templateOptions: HmiTrendTemplateOption[] = [];
  templateLoadOptions1Mask?: HmiProperty<number>;
  templateLoadOptions2Mask?: HmiProperty<number>;
  templateLoadOptions3Mask?: HmiProperty<number>;
  readonly batches: HmiTrendBatch[] = [];
  minimumValue?: HmiProperty<number>;
  maximumValue?: HmiProperty<number>;
  chartStyle?: HmiProperty<HmiTrendChartStyle>;
  containerType?: HmiProperty<HmiTrendContainerType>;
  xAxisPenNumber?: HmiProperty<number>;
  updateMode?: HmiProperty<HmiTrendUpdateMode>;
  refreshRateMilliseconds?: HmiProperty<number>;
  heartbeatMilliseconds?: HmiProperty<number>;
  deadbandPercent?: HmiProperty<number>;
  timeFormat?: HmiProperty<HmiTrendTimeFormat>;
  numericRadix?: HmiProperty<HmiTrendNumericRadix>;
  dataPointConnection?: HmiProperty<HmiTrendDataPointConnection>;
  displayMilliseconds?: HmiProperty<boolean>;
  /** Whether the chart time label shows elapsed time instead of clock time. */
  displayElapsedTime?: HmiProperty<boolean>;
  displayPenIcons?: HmiProperty<boolean>;
  useTrendNameAsLabel?: HmiProperty<boolean>;
  allowScrolling?: HmiProperty<boolean>;
  scrollMode?: HmiProperty<HmiTrendScrollMode>;
  displayScrollMechanism?: HmiProperty<boolean>;
  scrollMechanism?: HmiProperty<HmiTrendScrollMechanism>;
  bufferSizePerPen?: HmiProperty<number>;
  chartTitle?: string;
  chartTitleText?: HmiMultilingualText;
  displayChartTitle?: HmiProperty<boolean>;
  dataServerName?: string;
  dataServer?: HmiProperty<HmiTrendDataServer>;
  displayHistoricalLoadProgress?: HmiProperty<boolean>;
  displayLineLegend?: HmiProperty<boolean>;
  displayLineLegendMinimumMaximum?: HmiProperty<boolean>;
  lineLegendPenCaptionMode?: HmiProperty<HmiTrendPenCaptionMode>;
  lineLegendMaximumCaptionLength?: HmiProperty<number>;
  lineLegendPosition?: HmiProperty<HmiTrendLegendPosition>;
  lineLegendFirstVisibleRow?: HmiProperty<number>;
  lineLegendMaximumVisiblePens?: HmiProperty<number>;
  displayCurrentValueLegend?: HmiProperty<boolean>;
  currentValueLegendDisplayPenIcons?: HmiProperty<boolean>;
  currentValueLegendDisplayValues?: HmiProperty<boolean>;
  currentValueLegendDisplayTime?: HmiProperty<boolean>;
  /** Whether the interactive value bar is displayed on the chart. */
  displayValueBar?: HmiProperty<boolean>;
  /** Whether the value bar uses its configured color and width. */
  useGraphicValueBar?: HmiProperty<boolean>;
  valueBarColor?: HmiProperty<HmiColor>;
  valueBarWidth?: HmiProperty<number>;
  /** Whether the value bar extends into the time axis. */
  showValueBarInXAxis?: HmiProperty<boolean>;
  /** Whether the two statistics-area rulers are displayed. */
  displayStatisticRulers?: HmiProperty<boolean>;
  /** Whether statistics rulers use their configured color and width. */
  useGraphicStatisticRulers?: HmiProperty<boolean>;
  statisticRulerColor?: HmiProperty<HmiColor>;
  statisticRulerWidth?: HmiProperty<number>;
  xAxisScaleVisible?: HmiProperty<boolean>;
  xAxisColor?: HmiProperty<HmiColor>;
  /** Whether the time axis uses the first configured trend's color. */
  xAxisInTrendColor?: HmiProperty<boolean>;
  xAxisAlignment?: HmiProperty<HmiVerticalAlignment>;
  xAxisLabel?: string;
  xAxisDateVisible?: HmiProperty<boolean>;
  /** Time-axis date format using dd, MM, MMM, yy and yyyy tokens. */
  xAxisDateFormat?: HmiProperty<string>;
  xAxisGridVisible?: HmiProperty<boolean>;
  majorGridVisible?: HmiProperty<boolean>;
  majorGridColor?: HmiProperty<HmiColor>;
  minorGridVisible?: HmiProperty<boolean>;
  minorGridColor?: HmiProperty<HmiColor>;
  /** Whether the main grid uses the foreground pen color. */
  gridInTrendColor?: HmiProperty<boolean>;
  xAxisMajorGridLineCount?: HmiProperty<number>;
  xAxisMinorGridLineCount?: HmiProperty<number>;
  xAxisGridColor?: HmiProperty<HmiColor>;
  /** Engineering-system date text used at the left edge when scrolling is disabled. */
  xAxisStartDate?: string;
  /** Engineering-system time text used at the left edge when scrolling is disabled. */
  xAxisStartTime?: string;
  xAxisTimeSpan?: HmiProperty<number>;
  xAxisTimeSpanUnit?: string;
  timeBase?: HmiProperty<HmiTrendTimeBase>;
  /** Resolved project display zone (IANA ID, UTC, or Local), supplied by the host. */
  projectTimeZoneId?: string;
  yAxisRangeMode?: HmiProperty<HmiTrendYAxisRangeMode>;
  yAxisCustomMinimumSource?: HmiProperty<HmiTrendYAxisCustomBoundSource>;
  yAxisCustomMinimumValue?: HmiProperty<number>;
  yAxisCustomMinimumTagName?: string;
  yAxisCustomMaximumSource?: HmiProperty<HmiTrendYAxisCustomBoundSource>;
  yAxisCustomMaximumValue?: HmiProperty<number>;
  yAxisCustomMaximumTagName?: string;
  yAxisIsolatedGraphing?: HmiProperty<boolean>;
  yAxisIsolationPercent?: HmiProperty<number>;
  yAxisScaleVisible?: HmiProperty<boolean>;
  yAxisColor?: HmiProperty<HmiColor>;
  /** Whether the value axis uses the first configured trend's color. */
  yAxisInTrendColor?: HmiProperty<boolean>;
  yAxisAlignment?: HmiProperty<HmiHorizontalAlignment>;
  yAxisLabel?: string;
  yAxisDecimalPlaces?: HmiProperty<number>;
  yAxisGridVisible?: HmiProperty<boolean>;
  yAxisMajorGridLineCount?: HmiProperty<number>;
  yAxisMinorGridLineCount?: HmiProperty<number>;
  yAxisGridColor?: HmiProperty<HmiColor>;
  yAxisScaleMode?: HmiProperty<HmiTrendYAxisScaleMode>;
  yAxisScalePenNumber?: HmiProperty<number>;
  showPercentageAxis?: HmiProperty<boolean>;
  percentageAxisColor?: HmiProperty<HmiColor>;
  percentageAxisAlignment?: HmiProperty<HmiHorizontalAlignment>;
  /** @deprecated Use showPercentageAxis instead. */
  get yAxisScaleAsPercent(): HmiProperty<boolean> | undefined { return this.showPercentageAxis; }
  set yAxisScaleAsPercent(value: HmiProperty<boolean> | undefined) { this.showPercentageAxis = value; }
  /** @deprecated Use percentageAxisColor instead. */
  get yAxisPercentageColor(): HmiProperty<HmiColor> | undefined { return this.percentageAxisColor; }
  set yAxisPercentageColor(value: HmiProperty<HmiColor> | undefined) { this.percentageAxisColor = value; }
  yAxisSelectedPenScale?: HmiProperty<number>;
  readonly runtimePropertyTabs: string[] = [];
  runtimeAttributesEnabledMask?: HmiProperty<number>;
  allowEditingLegendProperties?: HmiProperty<boolean>;
  allowRuntimeContextMenu?: HmiProperty<boolean>;
  allowRuntimePenDragDrop?: HmiProperty<boolean>;
  runtimeTrendEnabled?: HmiProperty<boolean>;
  allowPanZoom?: HmiProperty<boolean>;
  allowPauseResumeScrolling?: HmiProperty<boolean>;
  allowShowHideValueBar?: HmiProperty<boolean>;
  allowSnapshotCreation?: HmiProperty<boolean>;
  allowOverlayOptions?: HmiProperty<boolean>;
  allowOverlayPropertyPage?: HmiProperty<boolean>;
  allowOverlayContextMenu?: HmiProperty<boolean>;
  allowPrint?: HmiProperty<boolean>;
  allowDeltaValueBar?: HmiProperty<boolean>;
  allowExportTrendData?: HmiProperty<boolean>;
  allowExportDataLogModelData?: HmiProperty<boolean>;
  showToolbar?: HmiProperty<boolean>;
  /** Whether the toolbar is aligned to the top or bottom edge. */
  toolbarAlignment?: HmiProperty<HmiVerticalAlignment>;
  useToolbarBackgroundColor?: HmiProperty<boolean>;
  toolbarFont?: HmiFont;
  toolbarForegroundColor?: HmiProperty<HmiColor>;
  toolbarBackgroundColor?: HmiProperty<HmiColor>;
  toolbarButtonSize?: HmiProperty<number>;
  showStatusBar?: HmiProperty<boolean>;
  useStatusBarBackgroundColor?: HmiProperty<boolean>;
  statusBarBackgroundColor?: HmiProperty<HmiColor>;
  statusBarForegroundColor?: HmiProperty<HmiColor>;
  statusBarFont?: HmiFont;
  statusBarText?: HmiMultilingualText;
  showStatusBarTooltips?: HmiProperty<boolean>;
  statusBarPanels: HmiTrendStatusBarPanel[] = [];
  showTimePeriodBar?: HmiProperty<boolean>;
  showTagExplorer?: HmiProperty<boolean>;
  collapseTagExplorer?: HmiProperty<boolean>;
  showTagList?: HmiProperty<boolean>;
  collapseTagList?: HmiProperty<boolean>;
  showXAxisCursors?: HmiProperty<boolean>;
  showYAxisCursors?: HmiProperty<boolean>;
  singleTraceMode?: HmiProperty<boolean>;
  rubberBandZoomEnabled?: HmiProperty<boolean>;
  timePeriodAbsoluteMode?: HmiProperty<boolean>;
  timePeriodDuration?: HmiProperty<string>;
  timePeriodStart?: HmiProperty<string>;
  timePeriodEnd?: HmiProperty<string>;
  showAlarmCursor?: HmiProperty<boolean>;
  showEventList?: HmiProperty<boolean>;
  collapseEventList?: HmiProperty<boolean>;
  legacyShowAlarmEventList?: HmiProperty<boolean>;
  legacyCollapseAlarmEventList?: HmiProperty<boolean>;
  activeTraceIndex?: HmiProperty<number>;
  activeBatchIndex?: HmiProperty<number>;
  activeTraceVisible?: HmiProperty<boolean>;
  activeTraceJoinPoints?: HmiProperty<boolean>;
  activeTraceLineColor?: HmiProperty<HmiColor>;
  activeTraceLineStyle?: HmiProperty<HmiLineStyle>;
  activeTraceLineWidth?: HmiProperty<number>;
  activeTraceDecimalFormat?: HmiProperty<boolean>;
  activeTraceNumericPrecision?: HmiProperty<number>;
  activePlottingAlgorithmLinear?: HmiProperty<boolean>;
  activeMarkerColor?: HmiProperty<HmiColor>;
  activeMarkerShape?: HmiProperty<number>;
  activeMarkerSize?: HmiProperty<number>;
  activeMarkerVisible?: HmiProperty<boolean>;
  activeXAxisColor?: HmiProperty<HmiColor>;
  activeXAxisGridLinesVisible?: HmiProperty<boolean>;
  activeXAxisLineWidth?: HmiProperty<number>;
  activeXAxisMajorTickScale?: HmiProperty<number>;
  activeXAxisMaximumValue?: HmiProperty<number>;
  activeXAxisMinorTickMarks?: HmiProperty<number>;
  activeXAxisMinimumValue?: HmiProperty<number>;
  activeXAxisScalingMode?: HmiProperty<HmiTrendAxisScalingMode>;
  activeXAxisVisible?: HmiProperty<boolean>;
  activeYAxisColor?: HmiProperty<HmiColor>;
  activeYAxisGridLinesVisible?: HmiProperty<boolean>;
  activeYAxisLineWidth?: HmiProperty<number>;
  activeYAxisMajorTickScale?: HmiProperty<number>;
  activeYAxisMaximumValue?: HmiProperty<number>;
  activeYAxisMinorTickMarks?: HmiProperty<number>;
  activeYAxisMinimumValue?: HmiProperty<number>;
  activeYAxisScalingMode?: HmiProperty<HmiTrendAxisScalingMode>;
  activeYAxisVisible?: HmiProperty<boolean>;
  controlType?: string;
  currentTagName?: string;
  currentXTagName?: string;
  currentYTagName?: string;
  useCustomFileExplorer?: HmiProperty<boolean>;
  autoScale?: HmiProperty<boolean>;
  chartLiveMode?: HmiProperty<boolean>;
  chartZoomPercent?: HmiProperty<number>;
  stackAxesMode?: HmiProperty<HmiTrendStackAxesMode>;
  windowBackgroundColor?: HmiProperty<HmiColor>;
  windowStyle?: HmiProperty<HmiTrendWindowStyle>;
  layoutLocked?: HmiProperty<boolean>;
  xAxisFlipped?: HmiProperty<boolean>;
  yAxisFlipped?: HmiProperty<boolean>;
  axesLocked?: HmiProperty<boolean>;
  displayOverlayZoomPanel?: HmiProperty<boolean>;
  showOutsidePoints?: HmiProperty<boolean>;
  showToolTip?: HmiProperty<boolean>;
  toolTipShowValue?: HmiProperty<boolean>;
  toolTipShowTime?: HmiProperty<boolean>;
  toolTipShowQuality?: HmiProperty<boolean>;
  chartTitleFont?: HmiFont;
  plotAreaMargin?: HmiThickness;
  backgroundPicturePath?: string;
  activePlotAsTitle?: HmiProperty<boolean>;
  plotScalingMethod?: string;
  defaultScalingMode?: string;
  axesPosition?: string;
  timeAlignment?: string;
  showCursorTimeDifference?: HmiProperty<boolean>;
  showCursorValueDifference?: HmiProperty<boolean>;
  displayQualifiedTagNames?: HmiProperty<boolean>;
  highlightActive?: HmiProperty<boolean>;
  highlightLineColor?: HmiProperty<HmiColor>;
  highlightLineStyle?: HmiProperty<HmiLineStyle>;
  highlightLineWidth?: HmiProperty<number>;
  traceDimmingMode?: string;
  meanLineColor?: HmiProperty<HmiColor>;
  zone1Color?: HmiProperty<HmiColor>;
  zone2Color?: HmiProperty<HmiColor>;
  zone3Color?: HmiProperty<HmiColor>;
  showZoneLines?: HmiProperty<boolean>;
  showZones?: HmiProperty<boolean>;
  displayRetrievedDataOnTrend?: HmiProperty<boolean>;
  retrievalTimeZoneId?: string;
  liveDataTimeDeadbandTicks?: HmiProperty<number>;
  liveDataMaximumAgeTicks?: HmiProperty<number>;
  liveDataMaximumElements?: HmiProperty<number>;
  liveDataStopWhenFull?: HmiProperty<boolean>;
  liveDataCollectorSizeType?: HmiProperty<number>;
}
