import { HmiColor } from "./HmiColor.js";
import { HmiFont } from "./HmiFont.js";
import { HmiHorizontalAlignment } from "./HmiHorizontalAlignment.js";
import { HmiProperty } from "./HmiProperty.js";
import { HmiThickness } from "./HmiThickness.js";
import { HmiVerticalAlignment } from "./HmiVerticalAlignment.js";

export class HmiVisualStyle {
  foregroundColor?: HmiProperty<HmiColor>;
  alternateForegroundColor?: HmiProperty<HmiColor>;
  backgroundColor?: HmiProperty<HmiColor>;
  alternateBackgroundColor?: HmiProperty<HmiColor>;
  borderColor?: HmiProperty<HmiColor>;
  borderBackgroundColor?: HmiProperty<HmiColor>;
  alternateBorderColor?: HmiProperty<HmiColor>;
  borderWidth?: HmiProperty<number>;
  borderStyle?: HmiProperty<number>;
  lineColor?: HmiProperty<HmiColor>;
  alternateLineColor?: HmiProperty<HmiColor>;
  lineWidth?: HmiProperty<number>;
  dashType?: HmiProperty<number>;
  backFillPattern?: HmiProperty<number>;
  cornerRadius?: HmiProperty<number>;
  cornerStyle?: HmiProperty<number>;
  edgeStyle?: HmiProperty<number>;
  captionColor?: HmiProperty<HmiColor>;
  captionBackgroundColor?: HmiProperty<HmiColor>;
  headerBackgroundColor?: HmiProperty<HmiColor>;
  headerForegroundColor?: HmiProperty<HmiColor>;
  contentBackgroundColor?: HmiProperty<HmiColor>;
  contentForegroundColor?: HmiProperty<HmiColor>;
  selectionBackgroundColor?: HmiProperty<HmiColor>;
  selectionForegroundColor?: HmiProperty<HmiColor>;
  evenRowBackgroundColor?: HmiProperty<HmiColor>;
  selectionBorderColor?: HmiProperty<HmiColor>;
  selectionBorderWidth?: HmiProperty<number>;
  focusColor?: HmiProperty<HmiColor>;
  focusWidth?: HmiProperty<number>;
  labelColor?: HmiProperty<HmiColor>;
  scaleBackgroundColor?: HmiProperty<HmiColor>;
  scaleForegroundColor?: HmiProperty<HmiColor>;
  tickColor?: HmiProperty<HmiColor>;
  thumbBackgroundColor?: HmiProperty<HmiColor>;
  thumbForegroundColor?: HmiProperty<HmiColor>;
  transparentColor?: HmiProperty<HmiColor>;
  useTransparentColor?: HmiProperty<boolean>;
  firstGradientColor?: HmiProperty<HmiColor>;
  firstGradientOffset?: HmiProperty<number>;
  middleGradientColor?: HmiProperty<HmiColor>;
  secondGradientColor?: HmiProperty<HmiColor>;
  secondGradientOffset?: HmiProperty<number>;
  useFirstGradient?: HmiProperty<boolean>;
  useSecondGradient?: HmiProperty<boolean>;
  useDesignColorSchema?: HmiProperty<boolean>;
  useDesignShadowSettings?: HmiProperty<boolean>;
  margin?: HmiThickness;
  padding?: HmiThickness;
  font?: HmiFont;
  headerFont?: HmiFont;
  contentFont?: HmiFont;
  labelFont?: HmiFont;
  horizontalAlignment?: HmiProperty<HmiHorizontalAlignment>;
  verticalAlignment?: HmiProperty<HmiVerticalAlignment>;
}
